AM_CPPFLAGS = -I$(top_builddir) -I$(top_srcdir)
AM_CXXFLAGS = 

if INTEGRATED_SST_CORE
AM_CPPFLAGS += $(SST_CPPFLAGS)
AM_CXXFLAGS += $(SST_CXXFLAGS)
endif

if EXTERNAL_BOOST
  AM_CPPFLAGS += $(BOOST_CPPFLAGS)
else
  AM_CPPFLAGS += -I$(top_srcdir)/boost
endif

