#! /usr/bin/env python

from gnuplot import *
from analyze import *


def getVals(fileName):
  import re
  text = open(fileName).read()
  regexp = re.compile("throughput=\s+(\d+[.]\d+)")
  matches = regexp.findall(text)
  return map(float, matches)


vals3 = getVals("amm3.out")
vals4 = getVals("amm4.out")

data = DataSet()
length = len(vals3)
for i in range(length):
  v3 = vals3[i]
  v4 = vals4[i]
  dp = DataPoint(v4)
  dp.add_properties(amm3=v3)
  data.add_point(dp)

plot = Plot("amm3")
plot.add(data, title =  None, color=Plot.blue, shape = Plot.circle, line=Plot.solid, curve=Plot.noline, size=1, width=1)
plot.add_trend_line(1)

plot.plot(xlabel="amm3", ylabel="amm4", output="plot.ps", xmin=0, ymin=0, xmax=10, ymax=10)

os.system("ps2pdf plot.ps")


