AM_CPPFLAGS = -I$(top_builddir) -I$(top_srcdir) -I$(top_srcdir)/sprockit -I$(top_builddir)/sprockit
AM_LDFLAGS = 

if USE_CUSTOM_NEW
AM_CPPFLAGS += -DUSE_CUSTOM_NEW -include sprockit/spkt_new.h
endif

if EXTERNAL_BOOST
  AM_CPPFLAGS += $(BOOST_CPPFLAGS)
endif

AM_CPPFLAGS += $(PTH_CPPFLAGS)
AM_LDFLAGS += $(PTH_LDFLAGS)

