#! /usr/bin/env python

files = []

import os
import commands

files.extend(commands.getoutput("git ls-files").splitlines())

for folder in "dumpi", "sumi", "sprockit":
  os.chdir(folder)
  manifest = commands.getoutput("git ls-files").splitlines()
  for file in manifest:
    files.append(os.path.join(folder, file))
  os.chdir("..")

open("sstmacro.files", "w").write("\n".join(files))

