#! /usr/bin/env python

import sys
import signal
import time
import os
import subprocess
import re
from configlib import getstatusoutput

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

tmpFile = sys.argv[1]
srcdir = sys.argv[2]
chkFile = tmpFile.replace("tmp", "chk")
refFile = os.path.join(srcdir, "tests", "reference", tmpFile.replace("tmp","ref"))
rc, output = getstatusoutput("diff %s %s" % (refFile, tmpFile))
text = ""
if not os.path.isfile(refFile):
  text = "FAILED: %s: no ref file" % (refFile)
  print (bcolors.FAIL + text + bcolors.ENDC)
elif rc == 0:
  text = "PASSED: %s" % chkFile
  print (bcolors.OKGREEN + text + bcolors.ENDC)
else:
  text = "FAILED: %s: files are different" % (chkFile)
  print (bcolors.FAIL + text + bcolors.ENDC)
open(chkFile,"w").write(text)

