.PHONY: histogram ftq spyplot parallel_histogram parallel_spyplot bytes_sent
if !INTEGRATED_SST_CORE
#------------------------------------------------------------------------------------------#
#  Stats tests                                                                          {{{#
#------------------------------------------------------------------------------------------#

STATSTESTS = \
  test_stats_msg_size_histogram \
  test_stats_spyplot \
  test_stats_bytes_sent \
  test_stats_bytes_sent_fattree \
  test_stats_bytes_sent_dfly \
  histogram.p \
  histogram.dat \
  test_stats_ftq \
  ftq_app1.p \
  ftq_app1.dat \
  spyplot.bytes.csv \
  spyplot.bytes.png \
  spyplot.num_messages.csv \
  spyplot.num_messages.png \
  bytes_on_port.dat \
  bytes_on_port_fattree.dat 

#  bytes_on_port_dfly.dat

if DO_GRAPHVIZ_TEST
SINGLETESTS += test_stat_graphviz test.callgrind
endif

test_stat_graphviz.$(CHKSUF): $(SSTMACEXEC)
	SSTMAC_THREADING=pthread $(SSTMACEXEC) \
         -f $(srcdir)/test_configs/test_ping_all_torus_pflow.ini \
         --no-wall-time \
         -p "call_graph=test" \
         -p mpi_test_print_all=false > $@
	-mv -f test.callgrind.out test.callgrind.chk-out

histogram:
	$(PYRUNTEST) 5 test_stats_msg_size_histogram.$(CHKSUF) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_msg_size_histogram.ini --low-res-timer --no-wall-time 
	-mv -f histogram.p histogram.p.$(CHKSUF)
	-mv -f histogram.dat histogram.dat.$(CHKSUF)
test_stats_msg_size_histogram.$(CHKSUF): histogram
histogram.dat.$(CHKSUF): histogram
histogram.p.$(CHKSUF): histogram

spyplot:
	$(PYRUNTEST) 5 test_stats_spyplot.$(CHKSUF) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_spyplot.ini --low-res-timer --no-wall-time  
	-mv -f spyplot.bytes.png spyplot.bytes.png.$(CHKSUF)
	-mv -f spyplot.bytes.csv spyplot.bytes.csv.$(CHKSUF)
	-mv -f spyplot.num_messages.png spyplot.num_messages.png.$(CHKSUF)
	-mv -f spyplot.num_messages.csv spyplot.num_messages.csv.$(CHKSUF)
test_stats_spyplot.$(CHKSUF): spyplot
spyplot.bytes.png.$(CHKSUF): spyplot
spyplot.bytes.csv.$(CHKSUF): spyplot
spyplot.num_messages.png.$(CHKSUF): spyplot
spyplot.num_messages.csv.$(CHKSUF): spyplot

ftq:
	$(PYRUNTEST) 5 test_stats_ftq.$(CHKSUF) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_ftq.ini --low-res-timer --no-wall-time  
	-mv -f ftq_app1.p ftq_app1.p.$(CHKSUF)
	-mv -f ftq_app1.dat ftq_app1.dat.$(CHKSUF)
test_stats_ftq.$(CHKSUF): ftq
ftq_app1.dat.$(CHKSUF): ftq
ftq_app1.p.$(CHKSUF): ftq

parallel_histogram:
	@launcher_test_args@ $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_msg_size_histogram.ini @mt_cmdline_args@ --low-res-timer --no-wall-time > test_stats_msg_size_histogram.$(CHKSUF)
	mv -f parallel_histogram.p   parallel_histogram.p.$(CHKSUF)
	mv -f parallel_histogram.dat parallel_histogram.dat.$(CHKSUF)
parallel_test_stats_msg_size_histogram.$(CHKSUF): parallel_histogram
parallel_histogram.dat.$(CHKSUF): parallel_histogram
parallel_histogram.p.$(CHKSUF): parallel_histogram

parallel_spyplot:
	@launcher_test_args@ $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_spyplot.ini @mt_cmdline_args@ --low-res-timer --no-wall-time > test_stats_spyplot.$(CHKSUF)
	mv -f parallel_spyplot.bytes.png parallel_spyplot.bytes.png.$(CHKSUF)
	mv -f parallel_spyplot.bytes.csv parallel_spyplot.bytes.csv.$(CHKSUF)
	mv -f parallel_spyplot.num_messages.png parallel_spyplot.num_messages.png.$(CHKSUF)
	mv -f parallel_spyplot.num_messages.csv parallel_spyplot.num_messages.csv.$(CHKSUF)
parallel_test_stats_spyplot.$(CHKSUF): parallel_spyplot
parallel_spyplot.bytes.png.$(CHKSUF): parallel_spyplot
parallel_spyplot.bytes.csv.$(CHKSUF): parallel_spyplot
parallel_spyplot.num_messages.png.$(CHKSUF): parallel_spyplot
parallel_spyplot.num_messages.csv.$(CHKSUF): parallel_spyplot

bytes_sent:
	$(PYRUNTEST) 5 test_stats_bytes_sent.$(CHKSUF) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_bytes_sent.ini --low-res-timer --no-wall-time  
	$(PYRUNTEST) 5 test_stats_bytes_sent_fattree.$(CHKSUF) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_bytes_sent_fattree.ini --low-res-timer --no-wall-time  
	$(PYRUNTEST) 5 test_stats_bytes_sent_dfly.$(CHKSUF) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_stats_bytes_sent_dfly.ini --low-res-timer --no-wall-time  
	-mv -f bytes_on_port.dat bytes_on_port.dat.$(CHKSUF)
	-mv -f bytes_on_port_fattree.dat bytes_on_port_fattree.dat.$(CHKSUF)
	-mv -f bytes_on_port_dfly.dat bytes_on_port_dfly.dat.$(CHKSUF)
test_stats_bytes_sent.$(CHKSUF): bytes_sent
test_stats_bytes_sent_fattree.$(CHKSUF): bytes_sent
test_stats_bytes_sent_dfly.$(CHKSUF): bytes_sent
bytes_on_port.dat.$(CHKSUF): bytes_sent
bytes_on_port_fattree.dat.$(CHKSUF): bytes_sent
bytes_on_port_dfly.dat.$(CHKSUF): bytes_sent

#------------------------------------------------------------------------------------------#
endif

