.PHONY: skeletons

if !INTEGRATED_SST_CORE
#------------------------------------------------------------------------------------------#
#  Skeleton tests (installcheck)                                                        {{{#
#------------------------------------------------------------------------------------------#

# The CASES variables are used here to simplify the build rules

# These are run with the same rule
SKELETONCASES= \
  gtc \
  osu \
  lu \
  sweep3d \
  miniFE \
  HPCCG 

if EXTERNAL_BOOST
  SKELETONCASES += boxml
endif

SKELETONTESTS = $(SKELETONCASES:%=test_skeleton_%)

SKELETON_DEFINES=
if HAVE_ATOMIC_BUILTIN
  SKELETON_DEFINES += -DHAVE_ATOMIC_BUILTIN
endif

skeletons:
	rm -fr skeletons
	cp -fpR $(top_srcdir)/skeletons .
	chmod -R u+w skeletons # required for make distcheck (makes files r/o)

$(SKELETONCASES): skeletons
	cd skeletons/$@; PATH=$(bindir):$$PATH \
          SKELETON_DEFINES=$(SKELETON_DEFINES) $(MAKE)

test_skeleton_%.$(CHKSUF): % 
	$(top_srcdir)/bin/runtest 3 $@ ./skeletons/$*/run$* --help 

test_apps_%.$(CHKSUF): %
	$(top_srcdir)/bin/runtest 3 $@ ./skeletons/$*/runsst -f $(srcdir)/test_configs/test_$*_app.ini \
          --no-wall-time 

test_mpi_apps_%.$(CHKSUF): %
	$(top_srcdir)/bin/runtest 3 $@ ./skeletons/$*/runsst -f $(srcdir)/test_configs/test_$*_mpi.ini \
          --no-wall-time 

#------------------------------------------------------------------------------------------#
endif
