
#------------------------------------------------------------------------------------------#
#  Config tests                                                                         {{{#
#------------------------------------------------------------------------------------------#

# These are also run with the same rule
CONFIGTESTS = \
  test_configs_smp_pflow \
  test_configs_simple_switch \
  test_configs_edison_amm1 \
  test_configs_edison_amm2 \
  test_configs_edison_amm3 \
  test_configs_hopper_amm1 \
  test_configs_hopper_amm2 \
  test_configs_hopper_amm3 \
  test_configs_hopper_amm1_simple \
  test_configs_hopper_amm2_simple \
  test_configs_hopper_amm3_simple \
  test_configs_deepthought \
  test_configs_exa1_pflow \
  test_configs_exa1_simple \
  test_configs_exa2_pflow \
  test_configs_exa2_simple 



if !INTEGRATED_SST_CORE
CONFIGTESTS += test_configs_sequoia 

COVERAGETESTS = \
  test_feature_nic_contention \
  test_memory_leak \
  test_feature_excl_job_launcher \
  test_coverage_smp_pflow \
  test_coverage_simple_switch \
  test_coverage_edison_amm1 \
  test_coverage_edison_amm2 \
  test_coverage_edison_amm3 \
  test_mpi_only_coverage_edison_amm3 \
  test_coverage_hopper_amm1 \
  test_coverage_hopper_amm2 \
  test_coverage_hopper_amm3 \
  test_coverage_hopper_amm1_simple \
  test_coverage_hopper_amm2_simple \
  test_coverage_hopper_amm3_simple \
  test_coverage_deepthought \
  test_coverage_sequoia \
  test_coverage_exa1_pflow \
  test_coverage_exa1_simple \
  test_coverage_exa2_pflow \
  test_mpi_only_coverage_exa2_simple \
  test_coverage_exa2_simple 
else
COVERAGETESTS =
endif

#  test_configs_hopper_amm4 

test_coverage_%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True \
    $(MPI_LAUNCHER) $(SSTMACEXEC) -i mpi_coverage.ini -f $*.ini -i exa_mini_top.ini \
    --no-wall-time 

test_memory_leak.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f $(top_srcdir)/tests/test_configs/memory_leak.ini \
    -i exa_mini_top.ini -i edison_amm3.ini \
    --no-wall-time 

test_feature_%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f $(top_srcdir)/tests/test_configs/$*.ini \
    -i exa_mini_top.ini -i edison_amm3.ini \
    --no-wall-time 

test_mpi_only_coverage_%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f mpi_only_coverage.ini -i $*.ini -i exa_mini_top.ini \
    --no-wall-time 

test_configs_exa%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ 't > 1 and t < 1.2' \
    $(MPI_LAUNCHER) $(SSTMACEXEC) -f mpi_test_all.ini -i default.ini -i exa$*.ini -i exa_mini_top.ini \
    --no-wall-time

test_configs_smp_%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f smp_mpi_test.ini -i default.ini -i smp_$*.ini \
    --no-wall-time

test_configs_hopper_amm4.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ 't > 4 and t < 4.2' \
    $(SSTMACEXEC) -f mpi_test_all.ini -i default.ini -i hopper_amm4.ini \
    --no-wall-time

test_configs_%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ 't > 1 and t < 1.2' \
    $(MPI_LAUNCHER) $(SSTMACEXEC) -f mpi_test_all.ini -i default.ini -i $*.ini \
    --no-wall-time

test_mpi_stats_%.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ 't > 1 and t < 1.2' \
    $(SSTMACEXEC) -f mpi_stats.ini -i default.ini -i $*.ini \
    --no-wall-time


#------------------------------------------------------------------------------------------#
