#------------------------------------------------------------------------------------------#
#  Core tests                                                                           {{{#
#------------------------------------------------------------------------------------------#


CORETESTS+= \
  test_core_apps_ping_all_ns \
  test_core_apps_compute \
  test_core_apps_host_compute \
  test_core_apps_ping_all_uneven_tree \
  test_core_apps_ping_all_torus_netlink \
  test_core_apps_stop_time \
  test_core_apps_distributed_service \
  test_sumi_collective \
  test_core_apps_ping_all_tiled_dfly \
  test_core_apps_ping_all_tiled_torus \
  test_core_apps_ping_pong \
  test_core_apps_ping_pong_slow \
  test_core_apps_ping_pong_amm4 \
  test_core_apps_ping_pong_amm4_slow 

test_core_apps_compute.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 6 $(top_srcdir) $@ Exact \
    $(SSTMACEXEC) --no-wall-time -f $(srcdir)/test_configs/test_compute_api.ini 

test_sumi_%.$(CHKSUF): sumi/sst_%
	$(PYRUNTEST) 5 $(top_srcdir) $@ Exact sumi/sst_$* -f $(srcdir)/sumi/ini/test_sst_$*.ini --no-wall-time 

test_core_apps_ping_all_tiled_dfly.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ Exact \
   $(SSTMACEXEC) -f $(srcdir)/test_configs/test_ping_all_tiled_dfly.ini --no-wall-time 

test_core_apps_host_compute.$(CHKSUF): $(CORE_TEST_DEPS)
	$(PYRUNTEST) 20 $(top_srcdir) $@ 't>0.1' \
    $(MPI_LAUNCHER) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_host_compute.ini --no-wall-time $(THREAD_ARGS)

test_core_apps_ping_all_tiled_torus.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True $(SSTMACEXEC) -f $(srcdir)/test_configs/test_ping_all_tiled_torus.ini --no-wall-time

test_core_apps_ping_pong.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True $(SSTMACEXEC) -f $(srcdir)/test_configs/test_ping_pong.ini --no-wall-time

test_core_apps_ping_pong_slow.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True $(SSTMACEXEC) -f $(srcdir)/test_configs/test_ping_pong_slow.ini --no-wall-time

test_core_apps_ping_pong_amm4.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True $(SSTMACEXEC) -f $(srcdir)/test_configs/test_ping_pong_amm4.ini --no-wall-time

test_core_apps_ping_pong_amm4_slow.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 15 $(top_srcdir) $@ True $(SSTMACEXEC) -f $(srcdir)/test_configs/test_ping_pong_amm4_slow.ini --no-wall-time

test_core_apps_%.$(CHKSUF): $(CORE_TEST_DEPS)
	$(PYRUNTEST) 10 $(top_srcdir) $@ Exact \
    $(MPI_LAUNCHER) $(SSTMACEXEC) -f $(srcdir)/test_configs/test_$*.ini --no-wall-time $(THREAD_ARGS)

#------------------------------------------------------------------------------------------#
