
SKELETONCASES= 

#------------------------------------------------------------------------------------------#
#  Skeleton tests (installcheck)                                                        {{{#
#------------------------------------------------------------------------------------------#

if INTEGRATED_SST_CORE
if HAVE_CLANG
if BUILD_SUMI_MPI
SKELETONCASES += liblulesh libhpcg libcomd
endif
endif
else
if HAVE_CLANG
SKELETONCASES += relocation_ptr_test openmp template_global_test unique_ptr_test
if BUILD_SUMI_MPI
SKELETONCASES += lulesh2.0.3 hpcg-3.0 CoMD 
endif
endif

SKELETONCASES += \
  boxml 

if BUILD_SUMI_MPI
SKELETONCASES += \
  sst_component_example \
  traffic \
  multiapp \
  sendrecv \
  sendrecv_sst_so 

if !HAVE_UBUNTU
SKELETONCASES +=  matmul 
endif
endif

endif 
#### SUMI MPI

SKELETONTESTS = $(SKELETONCASES:%=test_skeleton_%)

skeletons:
	rm -fr skeletons
	cp -fpR $(top_srcdir)/skeletons .
	chmod -R u+w skeletons # required for make distcheck (makes files r/o)

pots:
	rm -fr pots
	cp -fpR $(top_srcdir)/skeletons/CoMD/pots .
	chmod -R u+w pots # required for make distcheck (makes files r/o)


if INTEGRATED_SST_CORE
.PHONY: skeletons pots
libcomd.so: skeletons
	cd skeletons/CoMD; PATH=$(bindir):$$PATH $(MAKE) libcomd.so

test_skeleton_libcomd.$(CHKSUF): libcomd.so pots
	SST_LIB_PATH=$(SST_LIB_PATH):$(PWD)/skeletons/CoMD \
	$(PYRUNTEST) 3 $(top_srcdir) $@ Exact \
    $(top_builddir)/bin/pysstmac skeletons/CoMD/libcomd.so -f skeletons/CoMD/parameters.ini 

skeletons/lulesh2.0.3/liblulesh.so: skeletons
	cd skeletons/lulesh2.0.3; PATH=$(bindir):$$PATH $(MAKE) liblulesh.so

test_skeleton_liblulesh.$(CHKSUF): skeletons/lulesh2.0.3/liblulesh.so
	SST_LIB_PATH=$(SST_LIB_PATH):$(PWD)/skeletons/lulesh2.0.3 \
    $(PYRUNTEST) 3 $(top_srcdir) $@ Exact \
    $(top_builddir)/bin/pysstmac skeletons/lulesh2.0.3/liblulesh.so -f skeletons/lulesh2.0.3/parameters.ini 

skeletons/hpcg-3.0/libhpcg.so: skeletons
	cd skeletons/hpcg-3.0; PATH=$(bindir):$$PATH $(MAKE) libhpcg.so

test_skeleton_libhpcg.$(CHKSUF): skeletons/hpcg-3.0/libhpcg.so
	SST_LIB_PATH=$(SST_LIB_PATH):$(PWD)/skeletons/hpcg-3.0 \
    $(PYRUNTEST) 3 $(top_srcdir) $@ Exact \
    $(top_builddir)/bin/pysstmac skeletons/hpcg-3.0/libhpcg.so -f skeletons/hpcg-3.0/parameters.ini 
else
.PHONY: skeletons pots
$(SKELETONCASES): skeletons
	cd skeletons/$@; PATH=$(bindir):$$PATH $(MAKE) 

test_skeleton_boxml.$(CHKSUF): boxml
	$(PYRUNTEST) 2 $(top_srcdir) $@ text=finalized \
    ./skeletons/boxml/runboxml \
    -f $(top_srcdir)/skeletons/boxml/example/parameters.ini \
    -p node.app1.boxml_boxfile=$(top_srcdir)/skeletons/boxml/example/ks.4.new.boxes.xml \
    -p node.app1.boxml_eventfiles=$(top_srcdir)/skeletons/boxml/example/test-mlmg-4-4.xml 

test_skeleton_%.$(CHKSUF): % 
	$(PYRUNTEST) 60 $(top_srcdir) $@ Exact \
    ./skeletons/$*/run$* -f $(top_srcdir)/skeletons/$*/parameters.ini --no-wall-time

test_skeleton_CoMD.$(CHKSUF): CoMD pots
	$(PYRUNTEST) 3 $(top_srcdir) $@ Exact \
    ./skeletons/CoMD/runCoMD -f $(top_srcdir)/skeletons/CoMD/parameters.ini --no-wall-time

test_skeleton_sst_component_example.$(CHKSUF): sst_component_example $(SSTMACEXEC)
	SST_LIB_PATH=skeletons/sst_component_example \
	 $(PYRUNTEST) 10 $(top_srcdir) $@ Exact \
   $(SSTMACEXEC) -f $(top_srcdir)/skeletons/sst_component_example/parameters.ini --no-wall-time

test_skeleton_sendrecv_sst_so.$(CHKSUF): sendrecv_sst_so $(SSTMACEXEC)
	SST_LIB_PATH=skeletons/sendrecv_sst_so \
	 $(PYRUNTEST) 3 $(top_srcdir) $@ Exact \
   $(SSTMACEXEC) -f $(top_srcdir)/skeletons/sendrecv_sst_so/parameters.ini --no-wall-time

test_apps_%.$(CHKSUF): %
	$(PYRUNTEST) 3 $(top_srcdir) $@ True \
    ./skeletons/$*/runsst -f $(srcdir)/test_configs/test_$*_app.ini --no-wall-time 

test_mpi_apps_%.$(CHKSUF): %
	$(PYRUNTEST) 3 $(top_srcdir) $@ True \
    ./skeletons/$*/runsst -f $(srcdir)/test_configs/test_$*_mpi.ini --no-wall-time 

endif

