.PHONY: traces
if !INTEGRATED_SST_CORE
# These are each run by a specific rule
SINGLETESTS = \
  test_uq \
  test_utilities \
  test_pthread \
  test_blas \
  test_scan \
  test_blas_finegrained \
  test_node_noise \
  test_compute

if ENABLE_DEBUG
SINGLETESTS += \
  test_dumpi_manager \
  test_dumpi_bgp
endif

test_scan.$(CHKSUF): test_scan
	$(PYRUNTEST) 20 $(top_srcdir) $@ True \
    ./test_scan --no-wall-time -f $(srcdir)/test_configs/test_scan.ini

test_uq.$(CHKSUF): test_uq
	$(PYRUNTEST) 6 $(top_srcdir) $@ True \
    ./test_uq -f $(srcdir)/test_configs/test_uq.ini

test_utilities.$(CHKSUF): test_utilities
	$(PYRUNTEST) 6 $(top_srcdir) $@ True ./test_utilities 

test_blas.$(CHKSUF): test_blas
	$(PYRUNTEST) 6 $(top_srcdir) $@ 't > 0.08 and t < 0.1' \
    ./test_blas --no-wall-time -f $(srcdir)/test_configs/test_compute_blas.ini 

test_blas_finegrained.$(CHKSUF): test_blas
	$(PYRUNTEST) 6 $(top_srcdir) $@ 't > 0.08 and t < 0.1' \
    ./test_blas --no-wall-time -f $(srcdir)/test_configs/test_compute_blas_finegrained.ini 

test_node_noise.$(CHKSUF): test_blas
	$(PYRUNTEST) 6 $(top_srcdir) $@ 't > 0.1 and t < 0.11' \
    ./test_blas --no-wall-time -f $(srcdir)/test_configs/test_compute_blas_node_noise.ini 

test_pthread.$(CHKSUF): test_pthread
	$(PYRUNTEST) 6 $(top_srcdir) $@ True \
    ./test_pthread --no-wall-time -f $(srcdir)/test_configs/pthread.ini 

test_compute.$(CHKSUF): $(SSTMACEXEC)
	$(PYRUNTEST) 6 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f $(srcdir)/test_configs/test_compute.ini --no-wall-time 

#------------------------------------------------------------------------------------------#
#  DUMPI-related tests                                                                  {{{#
#------------------------------------------------------------------------------------------#

SINGLETESTS += \
  test_parsedumpi

traces:
	rm -fr *.bin *.meta *.map
	cp -f $(top_srcdir)/tests/test_traces/* ./
	chmod u+w *.bin *.meta *.map # required for make distcheck (makes files r/o)

test_dumpi_manager.$(CHKSUF): $(SSTMACEXEC) traces
	$(PYRUNTEST) 5 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f $(srcdir)/test_configs/test_dumpi_manager.ini \
          -d indexing,allocation --no-wall-time 

test_dumpi_bgp.$(CHKSUF): $(SSTMACEXEC) traces
	$(PYRUNTEST) 5 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f $(srcdir)/test_configs/test_dumpi_bgp.ini \
          -d indexing,allocation --no-wall-time 

test_parsedumpi.$(CHKSUF): $(SSTMACEXEC) traces
	$(PYRUNTEST) 3 $(top_srcdir) $@ True \
    $(SSTMACEXEC) -f $(srcdir)/test_configs/test_parsedumpi.ini --no-wall-time 

endif

