
if !INTEGRATED_SST_CORE
EXTRA_CPPFLAGS = -I$(top_builddir)/sstmac/replacements \
 -I$(top_srcdir)/sstmac/replacements 

check_PROGRAMS = test_utilities test_pthread test_blas test_std_thread test_tls
test_utilities_SOURCES = test_utilities.cc
test_utilities_LDADD = $(CORE_LIBS)

noinst_LTLIBRARIES = libsstmac_test_pthread.la
test_pthread_SOURCES = dummy_pthread.cc
libsstmac_test_pthread_la_SOURCES = test_pthread.cc
test_pthread_LDADD = $(top_builddir)/sstmac/main/libsstmac_main.la \
  libsstmac_test_pthread.la \
  $(CORE_LIBS)

noinst_LTLIBRARIES += libsstmac_test_blas.la
test_blas_SOURCES = dummy_blas.cc
libsstmac_test_blas_la_SOURCES = test_blas.cc
test_blas_LDADD = libsstmac_test_blas.la \
  $(top_builddir)/sstmac/libraries/blas/libsstmac_blas.la \
  $(top_builddir)/sstmac/main/libsstmac_main.la \
  $(CORE_LIBS)


noinst_LTLIBRARIES += libsstmac_test_std_thread.la
test_std_thread_SOURCES = dummy_std_thread.cc
libsstmac_test_std_thread_la_SOURCES = test_std_thread.cc
libsstmac_test_std_thread_la_CPPFLAGS = $(EXTRA_CPPFLAGS) $(AM_CPPFLAGS)
test_std_thread_LDADD = libsstmac_test_std_thread.la \
  $(top_builddir)/sstmac/main/libsstmac_main.la \
  $(CORE_LIBS)

noinst_LTLIBRARIES += libsstmac_test_tls.la
test_tls_SOURCES = dummy_tls.cc
libsstmac_test_tls_la_SOURCES = test_tls.cc
libsstmac_test_tls_la_CPPFLAGS = $(EXTRA_CPPFLAGS) $(AM_CPPFLAGS)
test_tls_LDADD = libsstmac_test_tls.la \
  $(top_builddir)/sstmac/main/libsstmac_main.la \
  $(CORE_LIBS)

if BUILD_SUMI_MPI
check_PROGRAMS += test_scan test_uq

test_scan_SOURCES = test_scan.cc
test_scan_LDADD = $(CORE_LIBS)

test_uq_SOURCES = test_uq.c
test_uq_LDADD = $(CORE_LIBS)
nodist_EXTRA_test_uq_SOURCES = dummy.cxx
endif

endif


