#! /usr/bin/env python

import sys
import os

outputFile = sys.argv[1]
tmpFile = outputFile.replace("chk","tmp")
srcFile = ".".join(outputFile.split(".")[:-1])
cmd = "mv %s %s" % (srcFile, tmpFile)
print(cmd)
rc = os.system(cmd)
if not rc == 0:
  sys.exit(1)

