/** Make sure to undefine any existing macros */
#undef pthread_create
#undef pthread_join
#undef pthread_tryjoin_np
#undef pthread_timedjoin_np
#undef pthread_detach
#undef pthread_equal
#undef pthread_attr_init
#undef pthread_attr_destroy
#undef pthread_attr_getdetachstate
#undef pthread_attr_setdetachstate
#undef pthread_attr_getguardsize
#undef pthread_attr_setguardsize
#undef pthread_attr_getschedparam
#undef pthread_attr_setschedparam
#undef pthread_attr_getschedpolicy
#undef pthread_attr_setschedpolicy
#undef pthread_attr_getinheritsched
#undef pthread_attr_setinheritsched
#undef pthread_attr_getscope
#undef pthread_attr_setscope
#undef pthread_attr_getstackaddr
#undef pthread_attr_setstackaddr
#undef pthread_attr_getstacksize
#undef pthread_attr_setstacksize
#undef pthread_attr_getstack
#undef pthread_attr_setstack
#undef pthread_attr_setaffinity_np
#undef pthread_attr_getaffinity_np
#undef pthread_getattr_np
#undef pthread_setschedparam
#undef pthread_getschedparam
#undef pthread_setschedprio
#undef pthread_getname_np
#undef pthread_setname_np
#undef pthread_getconcurrency
#undef pthread_setconcurrency
#undef pthread_yield
#undef pthread_setaffinity_np
#undef pthread_getaffinity_np
#undef pthread_once
#undef pthread_setcancelstate
#undef pthread_setcanceltype
#undef pthread_cancel
#undef pthread_mutex_init
#undef pthread_mutex_destroy
#undef pthread_mutex_trylock
#undef pthread_mutex_lock
#undef pthread_mutex_timedlock
#undef pthread_mutex_unlock
#undef pthread_mutex_getprioceiling
#undef pthread_mutex_setprioceiling
#undef pthread_mutex_consistent
#undef pthread_mutex_consistent_np
#undef pthread_mutexattr_init
#undef pthread_mutexattr_destroy
#undef pthread_mutexattr_getpshared
#undef pthread_mutexattr_setpshared
#undef pthread_mutexattr_gettype
#undef pthread_mutexattr_settype
#undef pthread_mutexattr_getprotocol
#undef pthread_mutexattr_setprotocol
#undef pthread_mutexattr_getprioceiling
#undef pthread_mutexattr_setprioceiling
#undef pthread_mutexattr_getrobust
#undef pthread_mutexattr_getrobust_np
#undef pthread_mutexattr_setrobust
#undef pthread_mutexattr_setrobust_np
#undef pthread_rwlock_init
#undef pthread_rwlock_destroy
#undef pthread_rwlock_rdlock
#undef pthread_rwlock_tryrdlock
#undef pthread_rwlock_timedrdlock
#undef pthread_rwlock_wrlock
#undef pthread_rwlock_trywrlock
#undef pthread_rwlock_timedwrlock
#undef pthread_rwlock_unlock
#undef pthread_rwlockattr_init
#undef pthread_rwlockattr_destroy
#undef pthread_rwlockattr_getpshared
#undef pthread_rwlockattr_setpshared
#undef pthread_rwlockattr_getkind_np
#undef pthread_rwlockattr_setkind_np
#undef pthread_cond_init
#undef pthread_cond_destroy
#undef pthread_cond_signal
#undef pthread_cond_broadcast
#undef pthread_cond_wait
#undef pthread_cond_timedwait
#undef pthread_condattr_init
#undef pthread_condattr_destroy
#undef pthread_condattr_getpshared
#undef pthread_condattr_setpshared
#undef pthread_condattr_getclock
#undef pthread_condattr_setclock
#undef pthread_spin_init
#undef pthread_spin_destroy
#undef pthread_spin_lock
#undef pthread_spin_trylock
#undef pthread_spin_unlock
#undef pthread_barrier_init
#undef pthread_barrier_destroy
#undef pthread_barrier_wait
#undef pthread_barrierattr_init
#undef pthread_barrierattr_destroy
#undef pthread_barrierattr_getpshared
#undef pthread_barrierattr_setpshared
#undef pthread_key_create
#undef pthread_key_delete
#undef pthread_setspecific
#undef pthread_getcpuclockid
#undef pthread_atfork
#undef pthread_getspecific
#undef pthread_setspecific
#undef pthread_self
#undef pthread_kill

#undef PTHREAD_THREADS_MAX
#undef PTHREAD_KEYS_MAX
#undef PTHREAD_STACK_MIN
#undef PTHREAD_CREATE_DETACHED
#undef PTHREAD_CREATE_JOINABLE

#undef PTHREAD_ONCE_INIT
#undef PTHREAD_COND_INITIALIZER
#undef PTHREAD_MUTEX_INITIALIZER

#ifdef SSTMAC_SAVE_ONCE_INIT
#define PTHREAD_ONCE_INIT SSTMAC_SAVE_ONCE_INIT
#undef SSTMAC_SAVE_ONCE_INIT
#endif

#undef pthread_t
#undef pthread_attr_t
#undef pthread_key_t
#undef pthread_cond_t
#undef pthread_mutex_t
#undef pthread_once_t
#undef pthread_mutexattr_t

#undef PTHREAD_SCOPE_PROCESS
#undef PTHREAD_SCOPE_SYSTEM 

