#! /usr/bin/env python

num_ranks = 144
topology = [6, 6, 6]
num_coords = len(topology)

def compute_coords(rank):
    remainder = rank
    coords = [0] * num_coords
    frame = 1
    for i in range(num_coords):
        multiplier = frame
        frame *= topology[i]
        next_idx = remainder % frame
        next_idx /= multiplier
        coords[i] = next_idx
        remainder -= multiplier * next_idx
    return coords

str_arr = []

format = lambda x: "%2d" % x

str_arr = ["%d %d" % (num_ranks, num_coords)]
for i in range(num_ranks):
    coords = compute_coords(i)
    str_arr.append(" ".join(map(format, coords)))

text = "\n".join(str_arr)
open("coordinates.txt","w").write(text)

