/*
 *  This file is part of SST/macroscale:
 *               The macroscale architecture simulator from the SST suite.
 *  Copyright (c) 2009 Sandia Corporation.
 *  This software is distributed under the BSD License.
 *  Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
 *  the U.S. Government retains certain rights in this software.
 *  For more information, see the LICENSE file in the top
 *  SST/macroscale directory.
 */

#ifndef SSTMAC_SKELETONS_OTF2_TRACE_REPLAY_CALLBASE_H_
#define SSTMAC_SKELETONS_OTF2_TRACE_REPLAY_CALLBASE_H_

#include <sstmac/software/process/operating_system.h>
#include <sumi-mpi/mpi_api.h>
#include <otf2/otf2.h>
#include <string>
#include <functional>

#include "mpi_calls.h"

// forward declare
class OTF2TraceReplayApp;

class CallBase {
public:
    // Ctors
    CallBase();
    CallBase(OTF2TraceReplayApp*);
    CallBase(OTF2_LocationRef, OTF2_TimeStamp, OTF2TraceReplayApp*);
    CallBase(OTF2_LocationRef, OTF2_TimeStamp, OTF2_TimeStamp, OTF2TraceReplayApp*);
    virtual ~CallBase() {}

    // Methods
    sstmac::timestamp GetStart();
    sstmac::timestamp GetEnd();
    void SetTrigger(std::function<void()>);
    virtual bool IsReady();
    virtual void Trigger();
    virtual int GetID() = 0;
    virtual const char* ToString();

    // Members
    OTF2_TimeStamp start_time, end_time;
    OTF2_LocationRef location;
    MPI_Request request_id;
    std::function<void()> on_trigger;
    OTF2TraceReplayApp* app;
    bool isready;

    static void assert_call(CallBase* cb, std::string msg);

private:
    sstmac::timestamp convert_time(const OTF2_TimeStamp);
     static constexpr const char* _name = "CallBase";
};

/******************************************************************************
 * Preprocessors for CallBase implementations
 */

#define CREATE_CALL(name, call_id) \
    class name : public CallBase { \
    public: \
        name(): CallBase(NULL) { }; \
        name(OTF2TraceReplayApp* app) : CallBase(app) { }; \
        name(OTF2_LocationRef location, OTF2_TimeStamp time, OTF2TraceReplayApp* app=NULL) : CallBase(location, time, app) { } \
        static const int id = call_id; \
        virtual const char* ToString() { return _name; } \
		virtual int GetID() { return id; }\
    private: \
        static constexpr const char* _name = #name; \
    };

/*****************************************************************************/

CREATE_CALL(MpiAbortCall, ID_MPI_Abort)
CREATE_CALL(MpiAccumulateCall, ID_MPI_Accumulate)
CREATE_CALL(MpiAdderrorclassCall, ID_MPI_Add_error_class)
CREATE_CALL(MpiAdderrorcodeCall, ID_MPI_Add_error_code)
CREATE_CALL(MpiAdderrorstringCall, ID_MPI_Add_error_string)
CREATE_CALL(MpiAddressCall, ID_MPI_Address)
//CREATE_CALL(MpiAintaddCall, ID_MPI_Aint_add)
//CREATE_CALL(MpiAintdiffCall, ID_MPI_Aint_diff)
CREATE_CALL(MpiAllgatherCall, ID_MPI_Allgather)
CREATE_CALL(MpiAllgathervCall, ID_MPI_Allgatherv)
CREATE_CALL(MpiAllocmemCall, ID_MPI_Alloc_mem)
CREATE_CALL(MpiAllreduceCall, ID_MPI_Allreduce)
CREATE_CALL(MpiAlltoallCall, ID_MPI_Alltoall)
CREATE_CALL(MpiAlltoallvCall, ID_MPI_Alltoallv)
CREATE_CALL(MpiAlltoallwCall, ID_MPI_Alltoallw)
CREATE_CALL(MpiAttrdeleteCall, ID_MPI_Attr_delete)
CREATE_CALL(MpiAttrgetCall, ID_MPI_Attr_get)
CREATE_CALL(MpiAttrputCall, ID_MPI_Attr_put)
CREATE_CALL(MpiBarrierCall, ID_MPI_Barrier)
CREATE_CALL(MpiBcastCall, ID_MPI_Bcast)
CREATE_CALL(MpiBsendCall, ID_MPI_Bsend)
CREATE_CALL(MpiBsendinitCall, ID_MPI_Bsend_init)
CREATE_CALL(MpiBufferattachCall, ID_MPI_Buffer_attach)
CREATE_CALL(MpiBufferdetachCall, ID_MPI_Buffer_detach)
CREATE_CALL(MpiCancelCall, ID_MPI_Cancel)
CREATE_CALL(MpiCartcoordsCall, ID_MPI_Cart_coords)
CREATE_CALL(MpiCartcreateCall, ID_MPI_Cart_create)
CREATE_CALL(MpiCartgetCall, ID_MPI_Cart_get)
CREATE_CALL(MpiCartmapCall, ID_MPI_Cart_map)
CREATE_CALL(MpiCartrankCall, ID_MPI_Cart_rank)
CREATE_CALL(MpiCartshiftCall, ID_MPI_Cart_shift)
CREATE_CALL(MpiCartsubCall, ID_MPI_Cart_sub)
CREATE_CALL(MpiCartdimgetCall, ID_MPI_Cartdim_get)
CREATE_CALL(MpiCloseportCall, ID_MPI_Close_port)
CREATE_CALL(MpiCommacceptCall, ID_MPI_Comm_accept)
CREATE_CALL(MpiCommcallerrhandlerCall, ID_MPI_Comm_call_errhandler)
CREATE_CALL(MpiCommcompareCall, ID_MPI_Comm_compare)
CREATE_CALL(MpiCommconnectCall, ID_MPI_Comm_connect)
CREATE_CALL(MpiCommcreateCall, ID_MPI_Comm_create)
CREATE_CALL(MpiCommcreateerrhandlerCall, ID_MPI_Comm_create_errhandler)
//CREATE_CALL(MpiCommcreategroupCall, ID_MPI_Comm_create_group)
CREATE_CALL(MpiCommcreatekeyvalCall, ID_MPI_Comm_create_keyval)
CREATE_CALL(MpiCommdeleteattrCall, ID_MPI_Comm_delete_attr)
CREATE_CALL(MpiCommdisconnectCall, ID_MPI_Comm_disconnect)
CREATE_CALL(MpiCommdupCall, ID_MPI_Comm_dup)
//CREATE_CALL(MpiCommdupwithinfoCall, ID_MPI_Comm_dup_with_info)
CREATE_CALL(MpiCommfreeCall, ID_MPI_Comm_free)
CREATE_CALL(MpiCommfreekeyvalCall, ID_MPI_Comm_free_keyval)
CREATE_CALL(MpiCommgetattrCall, ID_MPI_Comm_get_attr)
CREATE_CALL(MpiCommgeterrhandlerCall, ID_MPI_Comm_get_errhandler)
//CREATE_CALL(MpiCommgetinfoCall, ID_MPI_Comm_get_info)
CREATE_CALL(MpiCommgetnameCall, ID_MPI_Comm_get_name)
CREATE_CALL(MpiCommgetparentCall, ID_MPI_Comm_get_parent)
CREATE_CALL(MpiCommgroupCall, ID_MPI_Comm_group)
//CREATE_CALL(MpiCommidupCall, ID_MPI_Comm_idup)
CREATE_CALL(MpiCommjoinCall, ID_MPI_Comm_join)
CREATE_CALL(MpiCommrankCall, ID_MPI_Comm_rank)
CREATE_CALL(MpiCommremotegroupCall, ID_MPI_Comm_remote_group)
CREATE_CALL(MpiCommremotesizeCall, ID_MPI_Comm_remote_size)
CREATE_CALL(MpiCommsetattrCall, ID_MPI_Comm_set_attr)
CREATE_CALL(MpiCommseterrhandlerCall, ID_MPI_Comm_set_errhandler)
//CREATE_CALL(MpiCommsetinfoCall, ID_MPI_Comm_set_info)
CREATE_CALL(MpiCommsetnameCall, ID_MPI_Comm_set_name)
CREATE_CALL(MpiCommsizeCall, ID_MPI_Comm_size)
CREATE_CALL(MpiCommspawnCall, ID_MPI_Comm_spawn)
CREATE_CALL(MpiCommspawnmultipleCall, ID_MPI_Comm_spawn_multiple)
CREATE_CALL(MpiCommsplitCall, ID_MPI_Comm_split)
//CREATE_CALL(MpiCommsplittypeCall, ID_MPI_Comm_split_type)
CREATE_CALL(MpiCommtestinterCall, ID_MPI_Comm_test_inter)
//CREATE_CALL(MpiCompareandswapCall, ID_MPI_Compare_and_swap)
CREATE_CALL(MpiDimscreateCall, ID_MPI_Dims_create)
//CREATE_CALL(MpiDistgraphcreateCall, ID_MPI_Dist_graph_create)
//CREATE_CALL(MpiDistgraphcreateadjacentCall, ID_MPI_Dist_graph_create_adjacent)
//CREATE_CALL(MpiDistgraphneighborsCall, ID_MPI_Dist_graph_neighbors)
//CREATE_CALL(MpiDistgraphneighborscountCall, ID_MPI_Dist_graph_neighbors_count)
CREATE_CALL(MpiErrhandlercreateCall, ID_MPI_Errhandler_create)
CREATE_CALL(MpiErrhandlerfreeCall, ID_MPI_Errhandler_free)
CREATE_CALL(MpiErrhandlergetCall, ID_MPI_Errhandler_get)
CREATE_CALL(MpiErrhandlersetCall, ID_MPI_Errhandler_set)
CREATE_CALL(MpiErrorclassCall, ID_MPI_Error_class)
CREATE_CALL(MpiErrorstringCall, ID_MPI_Error_string)
CREATE_CALL(MpiExscanCall, ID_MPI_Exscan)
//CREATE_CALL(MpiFetchandopCall, ID_MPI_Fetch_and_op)
//CREATE_CALL(MpiFilec2fCall, ID_MPI_File_c2f)
CREATE_CALL(MpiFilecallerrhandlerCall, ID_MPI_File_call_errhandler)
CREATE_CALL(MpiFilecloseCall, ID_MPI_File_close)
CREATE_CALL(MpiFilecreateerrhandlerCall, ID_MPI_File_create_errhandler)
CREATE_CALL(MpiFiledeleteCall, ID_MPI_File_delete)
//CREATE_CALL(MpiFilef2cCall, ID_MPI_File_f2c)
CREATE_CALL(MpiFilegetamodeCall, ID_MPI_File_get_amode)
CREATE_CALL(MpiFilegetatomicityCall, ID_MPI_File_get_atomicity)
CREATE_CALL(MpiFilegetbyteoffsetCall, ID_MPI_File_get_byte_offset)
CREATE_CALL(MpiFilegeterrhandlerCall, ID_MPI_File_get_errhandler)
CREATE_CALL(MpiFilegetgroupCall, ID_MPI_File_get_group)
CREATE_CALL(MpiFilegetinfoCall, ID_MPI_File_get_info)
CREATE_CALL(MpiFilegetpositionCall, ID_MPI_File_get_position)
CREATE_CALL(MpiFilegetpositionsharedCall, ID_MPI_File_get_position_shared)
CREATE_CALL(MpiFilegetsizeCall, ID_MPI_File_get_size)
CREATE_CALL(MpiFilegettypeextentCall, ID_MPI_File_get_type_extent)
CREATE_CALL(MpiFilegetviewCall, ID_MPI_File_get_view)
CREATE_CALL(MpiFileireadCall, ID_MPI_File_iread)
//CREATE_CALL(MpiFileireadallCall, ID_MPI_File_iread_all)
CREATE_CALL(MpiFileireadatCall, ID_MPI_File_iread_at)
//CREATE_CALL(MpiFileireadatallCall, ID_MPI_File_iread_at_all)
CREATE_CALL(MpiFileireadsharedCall, ID_MPI_File_iread_shared)
CREATE_CALL(MpiFileiwriteCall, ID_MPI_File_iwrite)
//CREATE_CALL(MpiFileiwriteallCall, ID_MPI_File_iwrite_all)
CREATE_CALL(MpiFileiwriteatCall, ID_MPI_File_iwrite_at)
//CREATE_CALL(MpiFileiwriteatallCall, ID_MPI_File_iwrite_at_all)
CREATE_CALL(MpiFileiwritesharedCall, ID_MPI_File_iwrite_shared)
CREATE_CALL(MpiFileopenCall, ID_MPI_File_open)
CREATE_CALL(MpiFilepreallocateCall, ID_MPI_File_preallocate)
CREATE_CALL(MpiFilereadCall, ID_MPI_File_read)
CREATE_CALL(MpiFilereadallCall, ID_MPI_File_read_all)
CREATE_CALL(MpiFilereadallbeginCall, ID_MPI_File_read_all_begin)
CREATE_CALL(MpiFilereadallendCall, ID_MPI_File_read_all_end)
CREATE_CALL(MpiFilereadatCall, ID_MPI_File_read_at)
CREATE_CALL(MpiFilereadatallCall, ID_MPI_File_read_at_all)
CREATE_CALL(MpiFilereadatallbeginCall, ID_MPI_File_read_at_all_begin)
CREATE_CALL(MpiFilereadatallendCall, ID_MPI_File_read_at_all_end)
CREATE_CALL(MpiFilereadorderedCall, ID_MPI_File_read_ordered)
CREATE_CALL(MpiFilereadorderedbeginCall, ID_MPI_File_read_ordered_begin)
CREATE_CALL(MpiFilereadorderedendCall, ID_MPI_File_read_ordered_end)
CREATE_CALL(MpiFilereadsharedCall, ID_MPI_File_read_shared)
CREATE_CALL(MpiFileseekCall, ID_MPI_File_seek)
CREATE_CALL(MpiFileseeksharedCall, ID_MPI_File_seek_shared)
CREATE_CALL(MpiFilesetatomicityCall, ID_MPI_File_set_atomicity)
CREATE_CALL(MpiFileseterrhandlerCall, ID_MPI_File_set_errhandler)
CREATE_CALL(MpiFilesetinfoCall, ID_MPI_File_set_info)
CREATE_CALL(MpiFilesetsizeCall, ID_MPI_File_set_size)
CREATE_CALL(MpiFilesetviewCall, ID_MPI_File_set_view)
CREATE_CALL(MpiFilesyncCall, ID_MPI_File_sync)
CREATE_CALL(MpiFilewriteCall, ID_MPI_File_write)
CREATE_CALL(MpiFilewriteallCall, ID_MPI_File_write_all)
CREATE_CALL(MpiFilewriteallbeginCall, ID_MPI_File_write_all_begin)
CREATE_CALL(MpiFilewriteallendCall, ID_MPI_File_write_all_end)
CREATE_CALL(MpiFilewriteatCall, ID_MPI_File_write_at)
CREATE_CALL(MpiFilewriteatallCall, ID_MPI_File_write_at_all)
CREATE_CALL(MpiFilewriteatallbeginCall, ID_MPI_File_write_at_all_begin)
CREATE_CALL(MpiFilewriteatallendCall, ID_MPI_File_write_at_all_end)
CREATE_CALL(MpiFilewriteorderedCall, ID_MPI_File_write_ordered)
CREATE_CALL(MpiFilewriteorderedbeginCall, ID_MPI_File_write_ordered_begin)
CREATE_CALL(MpiFilewriteorderedendCall, ID_MPI_File_write_ordered_end)
CREATE_CALL(MpiFilewritesharedCall, ID_MPI_File_write_shared)
CREATE_CALL(MpiFinalizeCall, ID_MPI_Finalize)
CREATE_CALL(MpiFinalizedCall, ID_MPI_Finalized)
CREATE_CALL(MpiFreememCall, ID_MPI_Free_mem)
CREATE_CALL(MpiGatherCall, ID_MPI_Gather)
CREATE_CALL(MpiGathervCall, ID_MPI_Gatherv)
CREATE_CALL(MpiGetCall, ID_MPI_Get)
//CREATE_CALL(MpiGetaccumulateCall, ID_MPI_Get_accumulate)
CREATE_CALL(MpiGetaddressCall, ID_MPI_Get_address)
CREATE_CALL(MpiGetcountCall, ID_MPI_Get_count)
CREATE_CALL(MpiGetelementsCall, ID_MPI_Get_elements)
//CREATE_CALL(MpiGetelementsxCall, ID_MPI_Get_elements_x)
//CREATE_CALL(MpiGetlibraryversionCall, ID_MPI_Get_library_version)
CREATE_CALL(MpiGetprocessornameCall, ID_MPI_Get_processor_name)
CREATE_CALL(MpiGetversionCall, ID_MPI_Get_version)
CREATE_CALL(MpiGraphcreateCall, ID_MPI_Graph_create)
CREATE_CALL(MpiGraphgetCall, ID_MPI_Graph_get)
CREATE_CALL(MpiGraphmapCall, ID_MPI_Graph_map)
CREATE_CALL(MpiGraphneighborsCall, ID_MPI_Graph_neighbors)
CREATE_CALL(MpiGraphneighborscountCall, ID_MPI_Graph_neighbors_count)
CREATE_CALL(MpiGraphdimsgetCall, ID_MPI_Graphdims_get)
CREATE_CALL(MpiGrequestcompleteCall, ID_MPI_Grequest_complete)
CREATE_CALL(MpiGrequeststartCall, ID_MPI_Grequest_start)
CREATE_CALL(MpiGroupcompareCall, ID_MPI_Group_compare)
CREATE_CALL(MpiGroupdifferenceCall, ID_MPI_Group_difference)
CREATE_CALL(MpiGroupexclCall, ID_MPI_Group_excl)
CREATE_CALL(MpiGroupfreeCall, ID_MPI_Group_free)
CREATE_CALL(MpiGroupinclCall, ID_MPI_Group_incl)
CREATE_CALL(MpiGroupintersectionCall, ID_MPI_Group_intersection)
CREATE_CALL(MpiGrouprangeexclCall, ID_MPI_Group_range_excl)
CREATE_CALL(MpiGrouprangeinclCall, ID_MPI_Group_range_incl)
CREATE_CALL(MpiGrouprankCall, ID_MPI_Group_rank)
CREATE_CALL(MpiGroupsizeCall, ID_MPI_Group_size)
CREATE_CALL(MpiGrouptranslateranksCall, ID_MPI_Group_translate_ranks)
CREATE_CALL(MpiGroupunionCall, ID_MPI_Group_union)
//CREATE_CALL(MpiIallgatherCall, ID_MPI_Iallgather)
//CREATE_CALL(MpiIallgathervCall, ID_MPI_Iallgatherv)
//CREATE_CALL(MpiIallreduceCall, ID_MPI_Iallreduce)
//CREATE_CALL(MpiIalltoallCall, ID_MPI_Ialltoall)
//CREATE_CALL(MpiIalltoallvCall, ID_MPI_Ialltoallv)
//CREATE_CALL(MpiIalltoallwCall, ID_MPI_Ialltoallw)
//CREATE_CALL(MpiIbarrierCall, ID_MPI_Ibarrier)
//CREATE_CALL(MpiIbcastCall, ID_MPI_Ibcast)
//CREATE_CALL(MpiIbsendCall, ID_MPI_Ibsend)
//CREATE_CALL(MpiIexscanCall, ID_MPI_Iexscan)
//CREATE_CALL(MpiIgatherCall, ID_MPI_Igather)
//CREATE_CALL(MpiIgathervCall, ID_MPI_Igatherv)
//CREATE_CALL(MpiImprobeCall, ID_MPI_Improbe)
//CREATE_CALL(MpiImrecvCall, ID_MPI_Imrecv)
//CREATE_CALL(MpiIneighborallgatherCall, ID_MPI_Ineighbor_allgather)
//CREATE_CALL(MpiIneighborallgathervCall, ID_MPI_Ineighbor_allgatherv)
//CREATE_CALL(MpiIneighboralltoallCall, ID_MPI_Ineighbor_alltoall)
//CREATE_CALL(MpiIneighboralltoallvCall, ID_MPI_Ineighbor_alltoallv)
//CREATE_CALL(MpiIneighboralltoallwCall, ID_MPI_Ineighbor_alltoallw)
CREATE_CALL(MpiInfocreateCall, ID_MPI_Info_create)
CREATE_CALL(MpiInfodeleteCall, ID_MPI_Info_delete)
CREATE_CALL(MpiInfodupCall, ID_MPI_Info_dup)
CREATE_CALL(MpiInfofreeCall, ID_MPI_Info_free)
CREATE_CALL(MpiInfogetCall, ID_MPI_Info_get)
CREATE_CALL(MpiInfogetnkeysCall, ID_MPI_Info_get_nkeys)
CREATE_CALL(MpiInfogetnthkeyCall, ID_MPI_Info_get_nthkey)
CREATE_CALL(MpiInfogetvaluelenCall, ID_MPI_Info_get_valuelen)
CREATE_CALL(MpiInfosetCall, ID_MPI_Info_set)
CREATE_CALL(MpiInitCall, ID_MPI_Init)
CREATE_CALL(MpiInitthreadCall, ID_MPI_Init_thread)
CREATE_CALL(MpiInitializedCall, ID_MPI_Initialized)
CREATE_CALL(MpiIntercommcreateCall, ID_MPI_Intercomm_create)
CREATE_CALL(MpiIntercommmergeCall, ID_MPI_Intercomm_merge)
CREATE_CALL(MpiIprobeCall, ID_MPI_Iprobe)
CREATE_CALL(MpiIrecvCall, ID_MPI_Irecv)
//CREATE_CALL(MpiIreduceCall, ID_MPI_Ireduce)
//CREATE_CALL(MpiIreducescatterCall, ID_MPI_Ireduce_scatter)
//CREATE_CALL(MpiIreducescatterblockCall, ID_MPI_Ireduce_scatter_block)
CREATE_CALL(MpiIrsendCall, ID_MPI_Irsend)
CREATE_CALL(MpiIsthreadmainCall, ID_MPI_Is_thread_main)
//CREATE_CALL(MpiIscanCall, ID_MPI_Iscan)
//CREATE_CALL(MpiIscatterCall, ID_MPI_Iscatter)
//CREATE_CALL(MpiIscattervCall, ID_MPI_Iscatterv)
CREATE_CALL(MpiIsendCall, ID_MPI_Isend)
CREATE_CALL(MpiIssendCall, ID_MPI_Issend)
CREATE_CALL(MpiKeyvalcreateCall, ID_MPI_Keyval_create)
CREATE_CALL(MpiKeyvalfreeCall, ID_MPI_Keyval_free)
CREATE_CALL(MpiLookupnameCall, ID_MPI_Lookup_name)
//CREATE_CALL(MpiMprobeCall, ID_MPI_Mprobe)
//CREATE_CALL(MpiMrecvCall, ID_MPI_Mrecv)
//CREATE_CALL(MpiNeighborallgatherCall, ID_MPI_Neighbor_allgather)
//CREATE_CALL(MpiNeighborallgathervCall, ID_MPI_Neighbor_allgatherv)
//CREATE_CALL(MpiNeighboralltoallCall, ID_MPI_Neighbor_alltoall)
//CREATE_CALL(MpiNeighboralltoallvCall, ID_MPI_Neighbor_alltoallv)
//CREATE_CALL(MpiNeighboralltoallwCall, ID_MPI_Neighbor_alltoallw)
//CREATE_CALL(MpiOpcommuteCall, ID_MPI_Op_commute)
CREATE_CALL(MpiOpcreateCall, ID_MPI_Op_create)
CREATE_CALL(MpiOpfreeCall, ID_MPI_Op_free)
CREATE_CALL(MpiOpenportCall, ID_MPI_Open_port)
CREATE_CALL(MpiPackCall, ID_MPI_Pack)
CREATE_CALL(MpiPackexternalCall, ID_MPI_Pack_external)
CREATE_CALL(MpiPackexternalsizeCall, ID_MPI_Pack_external_size)
CREATE_CALL(MpiPacksizeCall, ID_MPI_Pack_size)
//CREATE_CALL(MpiPcontrolCall, ID_MPI_Pcontrol)
CREATE_CALL(MpiProbeCall, ID_MPI_Probe)
CREATE_CALL(MpiPublishnameCall, ID_MPI_Publish_name)
CREATE_CALL(MpiPutCall, ID_MPI_Put)
CREATE_CALL(MpiQuerythreadCall, ID_MPI_Query_thread)
//CREATE_CALL(MpiRaccumulateCall, ID_MPI_Raccumulate)
CREATE_CALL(MpiRecvCall, ID_MPI_Recv)
CREATE_CALL(MpiRecvinitCall, ID_MPI_Recv_init)
CREATE_CALL(MpiReduceCall, ID_MPI_Reduce)
//CREATE_CALL(MpiReducelocalCall, ID_MPI_Reduce_local)
CREATE_CALL(MpiReducescatterCall, ID_MPI_Reduce_scatter)
//CREATE_CALL(MpiReducescatterblockCall, ID_MPI_Reduce_scatter_block)
CREATE_CALL(MpiRegisterdatarepCall, ID_MPI_Register_datarep)
CREATE_CALL(MpiRequestfreeCall, ID_MPI_Request_free)
CREATE_CALL(MpiRequestgetstatusCall, ID_MPI_Request_get_status)
//CREATE_CALL(MpiRgetCall, ID_MPI_Rget)
//CREATE_CALL(MpiRgetaccumulateCall, ID_MPI_Rget_accumulate)
//CREATE_CALL(MpiRputCall, ID_MPI_Rput)
CREATE_CALL(MpiRsendCall, ID_MPI_Rsend)
CREATE_CALL(MpiRsendinitCall, ID_MPI_Rsend_init)
CREATE_CALL(MpiScanCall, ID_MPI_Scan)
CREATE_CALL(MpiScatterCall, ID_MPI_Scatter)
CREATE_CALL(MpiScattervCall, ID_MPI_Scatterv)
CREATE_CALL(MpiSendCall, ID_MPI_Send)
CREATE_CALL(MpiSendinitCall, ID_MPI_Send_init)
CREATE_CALL(MpiSendrecvCall, ID_MPI_Sendrecv)
CREATE_CALL(MpiSendrecvreplaceCall, ID_MPI_Sendrecv_replace)
CREATE_CALL(MpiSsendCall, ID_MPI_Ssend)
CREATE_CALL(MpiSsendinitCall, ID_MPI_Ssend_init)
CREATE_CALL(MpiStartCall, ID_MPI_Start)
CREATE_CALL(MpiStartallCall, ID_MPI_Startall)
CREATE_CALL(MpiStatussetcancelledCall, ID_MPI_Status_set_cancelled)
CREATE_CALL(MpiStatussetelementsCall, ID_MPI_Status_set_elements)
//CREATE_CALL(MpiStatussetelementsxCall, ID_MPI_Status_set_elements_x)
//CREATE_CALL(MpiTcategorychangedCall, ID_MPI_T_category_changed)
//CREATE_CALL(MpiTcategorygetcategoriesCall, ID_MPI_T_category_get_categories)
//CREATE_CALL(MpiTcategorygetcvarsCall, ID_MPI_T_category_get_cvars)
//CREATE_CALL(MpiTcategorygetinfoCall, ID_MPI_T_category_get_info)
//CREATE_CALL(MpiTcategorygetnumCall, ID_MPI_T_category_get_num)
//CREATE_CALL(MpiTcategorygetpvarsCall, ID_MPI_T_category_get_pvars)
//CREATE_CALL(MpiTcvargetinfoCall, ID_MPI_T_cvar_get_info)
//CREATE_CALL(MpiTcvargetnumCall, ID_MPI_T_cvar_get_num)
//CREATE_CALL(MpiTcvarhandleallocCall, ID_MPI_T_cvar_handle_alloc)
//CREATE_CALL(MpiTcvarhandlefreeCall, ID_MPI_T_cvar_handle_free)
//CREATE_CALL(MpiTcvarreadCall, ID_MPI_T_cvar_read)
//CREATE_CALL(MpiTcvarwriteCall, ID_MPI_T_cvar_write)
//CREATE_CALL(MpiTenumgetinfoCall, ID_MPI_T_enum_get_info)
//CREATE_CALL(MpiTenumgetitemCall, ID_MPI_T_enum_get_item)
//CREATE_CALL(MpiTfinalizeCall, ID_MPI_T_finalize)
//CREATE_CALL(MpiTinitthreadCall, ID_MPI_T_init_thread)
//CREATE_CALL(MpiTpvargetinfoCall, ID_MPI_T_pvar_get_info)
//CREATE_CALL(MpiTpvargetnumCall, ID_MPI_T_pvar_get_num)
//CREATE_CALL(MpiTpvarhandleallocCall, ID_MPI_T_pvar_handle_alloc)
//CREATE_CALL(MpiTpvarhandlefreeCall, ID_MPI_T_pvar_handle_free)
//CREATE_CALL(MpiTpvarreadCall, ID_MPI_T_pvar_read)
//CREATE_CALL(MpiTpvarreadresetCall, ID_MPI_T_pvar_readreset)
//CREATE_CALL(MpiTpvarresetCall, ID_MPI_T_pvar_reset)
//CREATE_CALL(MpiTpvarsessioncreateCall, ID_MPI_T_pvar_session_create)
//CREATE_CALL(MpiTpvarsessionfreeCall, ID_MPI_T_pvar_session_free)
//CREATE_CALL(MpiTpvarstartCall, ID_MPI_T_pvar_start)
//CREATE_CALL(MpiTpvarstopCall, ID_MPI_T_pvar_stop)
//CREATE_CALL(MpiTpvarwriteCall, ID_MPI_T_pvar_write)
CREATE_CALL(MpiTestCall, ID_MPI_Test)
CREATE_CALL(MpiTestcancelledCall, ID_MPI_Test_cancelled)
CREATE_CALL(MpiTestallCall, ID_MPI_Testall)
CREATE_CALL(MpiTestanyCall, ID_MPI_Testany)
CREATE_CALL(MpiTestsomeCall, ID_MPI_Testsome)
CREATE_CALL(MpiTopotestCall, ID_MPI_Topo_test)
CREATE_CALL(MpiTypecommitCall, ID_MPI_Type_commit)
CREATE_CALL(MpiTypecontiguousCall, ID_MPI_Type_contiguous)
CREATE_CALL(MpiTypecreatedarrayCall, ID_MPI_Type_create_darray)
CREATE_CALL(MpiTypecreatehindexedCall, ID_MPI_Type_create_hindexed)
//CREATE_CALL(MpiTypecreatehindexedblockCall, ID_MPI_Type_create_hindexed_block)
CREATE_CALL(MpiTypecreatehvectorCall, ID_MPI_Type_create_hvector)
CREATE_CALL(MpiTypecreateindexedblockCall, ID_MPI_Type_create_indexed_block)
CREATE_CALL(MpiTypecreatekeyvalCall, ID_MPI_Type_create_keyval)
CREATE_CALL(MpiTypecreateresizedCall, ID_MPI_Type_create_resized)
CREATE_CALL(MpiTypecreatestructCall, ID_MPI_Type_create_struct)
CREATE_CALL(MpiTypecreatesubarrayCall, ID_MPI_Type_create_subarray)
CREATE_CALL(MpiTypedeleteattrCall, ID_MPI_Type_delete_attr)
CREATE_CALL(MpiTypedupCall, ID_MPI_Type_dup)
CREATE_CALL(MpiTypeextentCall, ID_MPI_Type_extent)
CREATE_CALL(MpiTypefreeCall, ID_MPI_Type_free)
CREATE_CALL(MpiTypefreekeyvalCall, ID_MPI_Type_free_keyval)
CREATE_CALL(MpiTypegetattrCall, ID_MPI_Type_get_attr)
CREATE_CALL(MpiTypegetcontentsCall, ID_MPI_Type_get_contents)
CREATE_CALL(MpiTypegetenvelopeCall, ID_MPI_Type_get_envelope)
CREATE_CALL(MpiTypegetextentCall, ID_MPI_Type_get_extent)
//CREATE_CALL(MpiTypegetextentxCall, ID_MPI_Type_get_extent_x)
CREATE_CALL(MpiTypegetnameCall, ID_MPI_Type_get_name)
CREATE_CALL(MpiTypegettrueextentCall, ID_MPI_Type_get_true_extent)
//CREATE_CALL(MpiTypegettrueextentxCall, ID_MPI_Type_get_true_extent_x)
CREATE_CALL(MpiTypehindexedCall, ID_MPI_Type_hindexed)
CREATE_CALL(MpiTypehvectorCall, ID_MPI_Type_hvector)
CREATE_CALL(MpiTypeindexedCall, ID_MPI_Type_indexed)
CREATE_CALL(MpiTypelbCall, ID_MPI_Type_lb)
CREATE_CALL(MpiTypematchsizeCall, ID_MPI_Type_match_size)
CREATE_CALL(MpiTypesetattrCall, ID_MPI_Type_set_attr)
CREATE_CALL(MpiTypesetnameCall, ID_MPI_Type_set_name)
CREATE_CALL(MpiTypesizeCall, ID_MPI_Type_size)
//CREATE_CALL(MpiTypesizexCall, ID_MPI_Type_size_x)
CREATE_CALL(MpiTypestructCall, ID_MPI_Type_struct)
CREATE_CALL(MpiTypeubCall, ID_MPI_Type_ub)
CREATE_CALL(MpiTypevectorCall, ID_MPI_Type_vector)
CREATE_CALL(MpiUnpackCall, ID_MPI_Unpack)
CREATE_CALL(MpiUnpackexternalCall, ID_MPI_Unpack_external)
CREATE_CALL(MpiUnpublishnameCall, ID_MPI_Unpublish_name)
CREATE_CALL(MpiWaitCall, ID_MPI_Wait)
CREATE_CALL(MpiWaitallCall, ID_MPI_Waitall)
CREATE_CALL(MpiWaitanyCall, ID_MPI_Waitany)
CREATE_CALL(MpiWaitsomeCall, ID_MPI_Waitsome)
//CREATE_CALL(MpiWinallocateCall, ID_MPI_Win_allocate)
//CREATE_CALL(MpiWinallocatesharedCall, ID_MPI_Win_allocate_shared)
//CREATE_CALL(MpiWinattachCall, ID_MPI_Win_attach)
CREATE_CALL(MpiWincallerrhandlerCall, ID_MPI_Win_call_errhandler)
CREATE_CALL(MpiWincompleteCall, ID_MPI_Win_complete)
CREATE_CALL(MpiWincreateCall, ID_MPI_Win_create)
//CREATE_CALL(MpiWincreatedynamicCall, ID_MPI_Win_create_dynamic)
CREATE_CALL(MpiWincreateerrhandlerCall, ID_MPI_Win_create_errhandler)
CREATE_CALL(MpiWincreatekeyvalCall, ID_MPI_Win_create_keyval)
CREATE_CALL(MpiWindeleteattrCall, ID_MPI_Win_delete_attr)
//CREATE_CALL(MpiWindetachCall, ID_MPI_Win_detach)
CREATE_CALL(MpiWinfenceCall, ID_MPI_Win_fence)
//CREATE_CALL(MpiWinflushCall, ID_MPI_Win_flush)
//CREATE_CALL(MpiWinflushallCall, ID_MPI_Win_flush_all)
//CREATE_CALL(MpiWinflushlocalCall, ID_MPI_Win_flush_local)
//CREATE_CALL(MpiWinflushlocalallCall, ID_MPI_Win_flush_local_all)
CREATE_CALL(MpiWinfreeCall, ID_MPI_Win_free)
CREATE_CALL(MpiWinfreekeyvalCall, ID_MPI_Win_free_keyval)
CREATE_CALL(MpiWingetattrCall, ID_MPI_Win_get_attr)
CREATE_CALL(MpiWingeterrhandlerCall, ID_MPI_Win_get_errhandler)
CREATE_CALL(MpiWingetgroupCall, ID_MPI_Win_get_group)
//CREATE_CALL(MpiWingetinfoCall, ID_MPI_Win_get_info)
CREATE_CALL(MpiWingetnameCall, ID_MPI_Win_get_name)
CREATE_CALL(MpiWinlockCall, ID_MPI_Win_lock)
//CREATE_CALL(MpiWinlockallCall, ID_MPI_Win_lock_all)
CREATE_CALL(MpiWinpostCall, ID_MPI_Win_post)
CREATE_CALL(MpiWinsetattrCall, ID_MPI_Win_set_attr)
CREATE_CALL(MpiWinseterrhandlerCall, ID_MPI_Win_set_errhandler)
//CREATE_CALL(MpiWinsetinfoCall, ID_MPI_Win_set_info)
CREATE_CALL(MpiWinsetnameCall, ID_MPI_Win_set_name)
//CREATE_CALL(MpiWinsharedqueryCall, ID_MPI_Win_shared_query)
CREATE_CALL(MpiWinstartCall, ID_MPI_Win_start)
//CREATE_CALL(MpiWinsyncCall, ID_MPI_Win_sync)
CREATE_CALL(MpiWintestCall, ID_MPI_Win_test)
CREATE_CALL(MpiWinunlockCall, ID_MPI_Win_unlock)
//CREATE_CALL(MpiWinunlockallCall, ID_MPI_Win_unlock_all)
CREATE_CALL(MpiWinwaitCall, ID_MPI_Win_wait)
CREATE_CALL(MpiWtickCall, ID_MPI_Wtick)
CREATE_CALL(MpiWtimeCall, ID_MPI_Wtime)

#undef CREATE_CALL

#endif /* SSTMAC_SKELETONS_OTF2_TRACE_REPLAY_CALLBASE_H_ */
