/**
Copyright 2009-2017 National Technology and Engineering Solutions of Sandia, 
LLC (NTESS).  Under the terms of Contract DE-NA-0003525, the U.S.  Government 
retains certain rights in this software.

Sandia National Laboratories is a multimission laboratory managed and operated
by National Technology and Engineering Solutions of Sandia, LLC., a wholly 
owned subsidiary of Honeywell International, Inc., for the U.S. Department of 
Energy's National Nuclear Security Administration under contract DE-NA0003525.

Copyright (c) 2009-2017, NTESS

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.

    * Neither the name of Sandia Corporation nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Questions? Contact sst-macro-help@sandia.gov
*/

#include <sstmac/skeletons/otf2_trace_replay/structures.h>
#include <sstmac/skeletons/otf2_trace_replay/callid.h>

MPINameIDMap MPI_call_to_id;

MPINameIDMap::MPINameIDMap() :
idMap({
   { "MPIX_Comm_agree",	ID_MPIX_Comm_agree },
   { "MPI_File_set_errhandler",	ID_MPI_File_set_errhandler },
   { "MPI_Rsend",	ID_MPI_Rsend },
   { "MPIX_Comm_failure_ack",	ID_MPIX_Comm_failure_ack },
   { "MPI_File_set_info",	ID_MPI_File_set_info },
   { "MPI_Rsend_init",	ID_MPI_Rsend_init },
   { "MPIX_Comm_failure_get_acked",	ID_MPIX_Comm_failure_get_acked },
   { "MPI_File_set_size",	ID_MPI_File_set_size },
   { "MPI_Scan",	ID_MPI_Scan },
   { "MPIX_Comm_revoke",	ID_MPIX_Comm_revoke },
   { "MPI_File_set_view",	ID_MPI_File_set_view },
   { "MPI_Scatter",	ID_MPI_Scatter },
   { "MPIX_Comm_shrink",	ID_MPIX_Comm_shrink },
   { "MPI_File_sync",	ID_MPI_File_sync },
   { "MPI_Scatterv",	ID_MPI_Scatterv },
   { "MPI_Abort",	ID_MPI_Abort },
   { "MPI_File_write",	ID_MPI_File_write },
   { "MPI_Send",	ID_MPI_Send },
   { "MPI_Accumulate",	ID_MPI_Accumulate },
   { "MPI_File_write_all",	ID_MPI_File_write_all },
   { "MPI_Send_init",	ID_MPI_Send_init },
   { "MPI_Add_error_class",	ID_MPI_Add_error_class },
   { "MPI_File_write_all_begin",	ID_MPI_File_write_all_begin },
   { "MPI_Sendrecv",	ID_MPI_Sendrecv },
   { "MPI_Add_error_code",	ID_MPI_Add_error_code },
   { "MPI_File_write_all_end",	ID_MPI_File_write_all_end },
   { "MPI_Sendrecv_replace",	ID_MPI_Sendrecv_replace },
   { "MPI_Add_error_string",	ID_MPI_Add_error_string },
   { "MPI_File_write_at",	ID_MPI_File_write_at },
   { "MPI_Ssend",	ID_MPI_Ssend },
   { "MPI_Address",	ID_MPI_Address },
   { "MPI_File_write_at_all",	ID_MPI_File_write_at_all },
   { "MPI_Ssend_init",	ID_MPI_Ssend_init },
   { "MPI_Aint_add",	ID_MPI_Aint_add },
   { "MPI_File_write_at_all_begin",	ID_MPI_File_write_at_all_begin },
   { "MPI_Start",	ID_MPI_Start },
   { "MPI_Aint_diff",	ID_MPI_Aint_diff },
   { "MPI_File_write_at_all_end",	ID_MPI_File_write_at_all_end },
   { "MPI_Startall",	ID_MPI_Startall },
   { "MPI_Allgather",	ID_MPI_Allgather },
   { "MPI_File_write_ordered",	ID_MPI_File_write_ordered },
   { "MPI_Status_set_cancelled",	ID_MPI_Status_set_cancelled },
   { "MPI_Allgatherv",	ID_MPI_Allgatherv },
   { "MPI_File_write_ordered_begin",	ID_MPI_File_write_ordered_begin },
   { "MPI_Status_set_elements",	ID_MPI_Status_set_elements },
   { "MPI_Alloc_mem",	ID_MPI_Alloc_mem },
   { "MPI_File_write_ordered_end",	ID_MPI_File_write_ordered_end },
   { "MPI_Status_set_elements_x",	ID_MPI_Status_set_elements_x },
   { "MPI_Allreduce",	ID_MPI_Allreduce },
   { "MPI_File_write_shared",	ID_MPI_File_write_shared },
   { "MPI_T_category_changed",	ID_MPI_T_category_changed },
   { "MPI_Alltoall",	ID_MPI_Alltoall },
   { "MPI_Finalize",	ID_MPI_Finalize },
   { "MPI_T_category_get_categories",	ID_MPI_T_category_get_categories },
   { "MPI_Alltoallv",	ID_MPI_Alltoallv },
   { "MPI_Finalized",	ID_MPI_Finalized },
   { "MPI_T_category_get_cvars",	ID_MPI_T_category_get_cvars },
   { "MPI_Alltoallw",	ID_MPI_Alltoallw },
   { "MPI_Free_mem",	ID_MPI_Free_mem },
   { "MPI_T_category_get_info",	ID_MPI_T_category_get_info },
   { "MPI_Attr_delete",	ID_MPI_Attr_delete },
   { "MPI_Gather",	ID_MPI_Gather },
   { "MPI_T_category_get_num",	ID_MPI_T_category_get_num },
   { "MPI_Attr_get",	ID_MPI_Attr_get },
   { "MPI_Gatherv",	ID_MPI_Gatherv },
   { "MPI_T_category_get_pvars",	ID_MPI_T_category_get_pvars },
   { "MPI_Attr_put",	ID_MPI_Attr_put },
   { "MPI_Get",	ID_MPI_Get },
   { "MPI_T_cvar_get_info",	ID_MPI_T_cvar_get_info },
   { "MPI_Barrier",	ID_MPI_Barrier },
   { "MPI_Get_accumulate",	ID_MPI_Get_accumulate },
   { "MPI_T_cvar_get_num",	ID_MPI_T_cvar_get_num },
   { "MPI_Bcast",	ID_MPI_Bcast },
   { "MPI_Get_address",	ID_MPI_Get_address },
   { "MPI_T_cvar_handle_alloc",	ID_MPI_T_cvar_handle_alloc },
   { "MPI_Bsend",	ID_MPI_Bsend },
   { "MPI_Get_count",	ID_MPI_Get_count },
   { "MPI_T_cvar_handle_free",	ID_MPI_T_cvar_handle_free },
   { "MPI_Bsend_init",	ID_MPI_Bsend_init },
   { "MPI_Get_elements",	ID_MPI_Get_elements },
   { "MPI_T_cvar_read",	ID_MPI_T_cvar_read },
   { "MPI_Buffer_attach",	ID_MPI_Buffer_attach },
   { "MPI_Get_elements_x",	ID_MPI_Get_elements_x },
   { "MPI_T_cvar_write",	ID_MPI_T_cvar_write },
   { "MPI_Buffer_detach",	ID_MPI_Buffer_detach },
   { "MPI_Get_library_version",	ID_MPI_Get_library_version },
   { "MPI_T_enum_get_info",	ID_MPI_T_enum_get_info },
   { "MPI_Cancel",	ID_MPI_Cancel },
   { "MPI_Get_processor_name",	ID_MPI_Get_processor_name },
   { "MPI_T_enum_get_item",	ID_MPI_T_enum_get_item },
   { "MPI_Cart_coords",	ID_MPI_Cart_coords },
   { "MPI_Get_version",	ID_MPI_Get_version },
   { "MPI_T_finalize",	ID_MPI_T_finalize },
   { "MPI_Cart_create",	ID_MPI_Cart_create },
   { "MPI_Graph_create",	ID_MPI_Graph_create },
   { "MPI_T_init_thread",	ID_MPI_T_init_thread },
   { "MPI_Cart_get",	ID_MPI_Cart_get },
   { "MPI_Graph_get",	ID_MPI_Graph_get },
   { "MPI_T_pvar_get_info",	ID_MPI_T_pvar_get_info },
   { "MPI_Cart_map",	ID_MPI_Cart_map },
   { "MPI_Graph_map",	ID_MPI_Graph_map },
   { "MPI_T_pvar_get_num",	ID_MPI_T_pvar_get_num },
   { "MPI_Cart_rank",	ID_MPI_Cart_rank },
   { "MPI_Graph_neighbors",	ID_MPI_Graph_neighbors },
   { "MPI_T_pvar_handle_alloc",	ID_MPI_T_pvar_handle_alloc },
   { "MPI_Cart_shift",	ID_MPI_Cart_shift },
   { "MPI_Graph_neighbors_count",	ID_MPI_Graph_neighbors_count },
   { "MPI_T_pvar_handle_free",	ID_MPI_T_pvar_handle_free },
   { "MPI_Cart_sub",	ID_MPI_Cart_sub },
   { "MPI_Graphdims_get",	ID_MPI_Graphdims_get },
   { "MPI_T_pvar_read",	ID_MPI_T_pvar_read },
   { "MPI_Cartdim_get",	ID_MPI_Cartdim_get },
   { "MPI_Grequest_complete",	ID_MPI_Grequest_complete },
   { "MPI_T_pvar_readreset",	ID_MPI_T_pvar_readreset },
   { "MPI_Close_port",	ID_MPI_Close_port },
   { "MPI_Grequest_start",	ID_MPI_Grequest_start },
   { "MPI_T_pvar_reset",	ID_MPI_T_pvar_reset },
   { "MPI_Comm_accept",	ID_MPI_Comm_accept },
   { "MPI_Group_compare",	ID_MPI_Group_compare },
   { "MPI_T_pvar_session_create",	ID_MPI_T_pvar_session_create },
   { "MPI_Comm_call_errhandler",	ID_MPI_Comm_call_errhandler },
   { "MPI_Group_difference",	ID_MPI_Group_difference },
   { "MPI_T_pvar_session_free",	ID_MPI_T_pvar_session_free },
   { "MPI_Comm_compare",	ID_MPI_Comm_compare },
   { "MPI_Group_excl",	ID_MPI_Group_excl },
   { "MPI_T_pvar_start",	ID_MPI_T_pvar_start },
   { "MPI_Comm_connect",	ID_MPI_Comm_connect },
   { "MPI_Group_free",	ID_MPI_Group_free },
   { "MPI_T_pvar_stop",	ID_MPI_T_pvar_stop },
   { "MPI_Comm_create",	ID_MPI_Comm_create },
   { "MPI_Group_incl",	ID_MPI_Group_incl },
   { "MPI_T_pvar_write",	ID_MPI_T_pvar_write },
   { "MPI_Comm_create_errhandler",	ID_MPI_Comm_create_errhandler },
   { "MPI_Group_intersection",	ID_MPI_Group_intersection },
   { "MPI_Test",	ID_MPI_Test },
   { "MPI_Comm_create_group",	ID_MPI_Comm_create_group },
   { "MPI_Group_range_excl",	ID_MPI_Group_range_excl },
   { "MPI_Test_cancelled",	ID_MPI_Test_cancelled },
   { "MPI_Comm_create_keyval",	ID_MPI_Comm_create_keyval },
   { "MPI_Group_range_incl",	ID_MPI_Group_range_incl },
   { "MPI_Testall",	ID_MPI_Testall },
   { "MPI_Comm_delete_attr",	ID_MPI_Comm_delete_attr },
   { "MPI_Group_rank",	ID_MPI_Group_rank },
   { "MPI_Testany",	ID_MPI_Testany },
   { "MPI_Comm_disconnect",	ID_MPI_Comm_disconnect },
   { "MPI_Group_size",	ID_MPI_Group_size },
   { "MPI_Testsome",	ID_MPI_Testsome },
   { "MPI_Comm_dup",	ID_MPI_Comm_dup },
   { "MPI_Group_translate_ranks",	ID_MPI_Group_translate_ranks },
   { "MPI_Topo_test",	ID_MPI_Topo_test },
   { "MPI_Comm_dup_with_info",	ID_MPI_Comm_dup_with_info },
   { "MPI_Group_union",	ID_MPI_Group_union },
   { "MPI_Type_commit",	ID_MPI_Type_commit },
   { "MPI_Comm_free",	ID_MPI_Comm_free },
   { "MPI_Iallgather",	ID_MPI_Iallgather },
   { "MPI_Type_contiguous",	ID_MPI_Type_contiguous },
   { "MPI_Comm_free_keyval",	ID_MPI_Comm_free_keyval },
   { "MPI_Iallgatherv",	ID_MPI_Iallgatherv },
   { "MPI_Type_create_darray",	ID_MPI_Type_create_darray },
   { "MPI_Comm_get_attr",	ID_MPI_Comm_get_attr },
   { "MPI_Iallreduce",	ID_MPI_Iallreduce },
   { "MPI_Type_create_hindexed",	ID_MPI_Type_create_hindexed },
   { "MPI_Comm_get_errhandler",	ID_MPI_Comm_get_errhandler },
   { "MPI_Ialltoall",	ID_MPI_Ialltoall },
   { "MPI_Type_create_hindexed_block",	ID_MPI_Type_create_hindexed_block },
   { "MPI_Comm_get_info",	ID_MPI_Comm_get_info },
   { "MPI_Ialltoallv",	ID_MPI_Ialltoallv },
   { "MPI_Type_create_hvector",	ID_MPI_Type_create_hvector },
   { "MPI_Comm_get_name",	ID_MPI_Comm_get_name },
   { "MPI_Ialltoallw",	ID_MPI_Ialltoallw },
   { "MPI_Type_create_indexed_block",	ID_MPI_Type_create_indexed_block },
   { "MPI_Comm_get_parent",	ID_MPI_Comm_get_parent },
   { "MPI_Ibarrier",	ID_MPI_Ibarrier },
   { "MPI_Type_create_keyval",	ID_MPI_Type_create_keyval },
   { "MPI_Comm_group",	ID_MPI_Comm_group },
   { "MPI_Ibcast",	ID_MPI_Ibcast },
   { "MPI_Type_create_resized",	ID_MPI_Type_create_resized },
   { "MPI_Comm_idup",	ID_MPI_Comm_idup },
   { "MPI_Ibsend",	ID_MPI_Ibsend },
   { "MPI_Type_create_struct",	ID_MPI_Type_create_struct },
   { "MPI_Comm_join",	ID_MPI_Comm_join },
   { "MPI_Iexscan",	ID_MPI_Iexscan },
   { "MPI_Type_create_subarray",	ID_MPI_Type_create_subarray },
   { "MPI_Comm_rank",	ID_MPI_Comm_rank },
   { "MPI_Igather",	ID_MPI_Igather },
   { "MPI_Type_delete_attr",	ID_MPI_Type_delete_attr },
   { "MPI_Comm_remote_group",	ID_MPI_Comm_remote_group },
   { "MPI_Igatherv",	ID_MPI_Igatherv },
   { "MPI_Type_dup",	ID_MPI_Type_dup },
   { "MPI_Comm_remote_size",	ID_MPI_Comm_remote_size },
   { "MPI_Improbe",	ID_MPI_Improbe },
   { "MPI_Type_extent",	ID_MPI_Type_extent },
   { "MPI_Comm_set_attr",	ID_MPI_Comm_set_attr },
   { "MPI_Imrecv",	ID_MPI_Imrecv },
   { "MPI_Type_free",	ID_MPI_Type_free },
   { "MPI_Comm_set_errhandler",	ID_MPI_Comm_set_errhandler },
   { "MPI_Ineighbor_allgather",	ID_MPI_Ineighbor_allgather },
   { "MPI_Type_free_keyval",	ID_MPI_Type_free_keyval },
   { "MPI_Comm_set_info",	ID_MPI_Comm_set_info },
   { "MPI_Ineighbor_allgatherv",	ID_MPI_Ineighbor_allgatherv },
   { "MPI_Type_get_attr",	ID_MPI_Type_get_attr },
   { "MPI_Comm_set_name",	ID_MPI_Comm_set_name },
   { "MPI_Ineighbor_alltoall",	ID_MPI_Ineighbor_alltoall },
   { "MPI_Type_get_contents",	ID_MPI_Type_get_contents },
   { "MPI_Comm_size",	ID_MPI_Comm_size },
   { "MPI_Ineighbor_alltoallv",	ID_MPI_Ineighbor_alltoallv },
   { "MPI_Type_get_envelope",	ID_MPI_Type_get_envelope },
   { "MPI_Comm_spawn",	ID_MPI_Comm_spawn },
   { "MPI_Ineighbor_alltoallw",	ID_MPI_Ineighbor_alltoallw },
   { "MPI_Type_get_extent",	ID_MPI_Type_get_extent },
   { "MPI_Comm_spawn_multiple",	ID_MPI_Comm_spawn_multiple },
   { "MPI_Info_create",	ID_MPI_Info_create },
   { "MPI_Type_get_extent_x",	ID_MPI_Type_get_extent_x },
   { "MPI_Comm_split",	ID_MPI_Comm_split },
   { "MPI_Info_delete",	ID_MPI_Info_delete },
   { "MPI_Type_get_name",	ID_MPI_Type_get_name },
   { "MPI_Comm_split_type",	ID_MPI_Comm_split_type },
   { "MPI_Info_dup",	ID_MPI_Info_dup },
   { "MPI_Type_get_true_extent",	ID_MPI_Type_get_true_extent },
   { "MPI_Comm_test_inter",	ID_MPI_Comm_test_inter },
   { "MPI_Info_free",	ID_MPI_Info_free },
   { "MPI_Type_get_true_extent_x",	ID_MPI_Type_get_true_extent_x },
   { "MPI_Compare_and_swap",	ID_MPI_Compare_and_swap },
   { "MPI_Info_get",	ID_MPI_Info_get },
   { "MPI_Type_hindexed",	ID_MPI_Type_hindexed },
   { "MPI_Dims_create",	ID_MPI_Dims_create },
   { "MPI_Info_get_nkeys",	ID_MPI_Info_get_nkeys },
   { "MPI_Type_hvector",	ID_MPI_Type_hvector },
   { "MPI_Dist_graph_create",	ID_MPI_Dist_graph_create },
   { "MPI_Info_get_nthkey",	ID_MPI_Info_get_nthkey },
   { "MPI_Type_indexed",	ID_MPI_Type_indexed },
   { "MPI_Dist_graph_create_adjacent",	ID_MPI_Dist_graph_create_adjacent },
   { "MPI_Info_get_valuelen",	ID_MPI_Info_get_valuelen },
   { "MPI_Type_lb",	ID_MPI_Type_lb },
   { "MPI_Dist_graph_neighbors",	ID_MPI_Dist_graph_neighbors },
   { "MPI_Info_set",	ID_MPI_Info_set },
   { "MPI_Type_match_size",	ID_MPI_Type_match_size },
   { "MPI_Dist_graph_neighbors_count",	ID_MPI_Dist_graph_neighbors_count },
   { "MPI_Init",	ID_MPI_Init },
   { "MPI_Type_set_attr",	ID_MPI_Type_set_attr },
   { "MPI_Errhandler_create",	ID_MPI_Errhandler_create },
   { "MPI_Init_thread",	ID_MPI_Init_thread },
   { "MPI_Type_set_name",	ID_MPI_Type_set_name },
   { "MPI_Errhandler_free",	ID_MPI_Errhandler_free },
   { "MPI_Initialized",	ID_MPI_Initialized },
   { "MPI_Type_size",	ID_MPI_Type_size },
   { "MPI_Errhandler_get",	ID_MPI_Errhandler_get },
   { "MPI_Intercomm_create",	ID_MPI_Intercomm_create },
   { "MPI_Type_size_x",	ID_MPI_Type_size_x },
   { "MPI_Errhandler_set",	ID_MPI_Errhandler_set },
   { "MPI_Intercomm_merge",	ID_MPI_Intercomm_merge },
   { "MPI_Type_struct",	ID_MPI_Type_struct },
   { "MPI_Error_class",	ID_MPI_Error_class },
   { "MPI_Iprobe",	ID_MPI_Iprobe },
   { "MPI_Type_ub",	ID_MPI_Type_ub },
   { "MPI_Error_string",	ID_MPI_Error_string },
   { "MPI_Irecv",	ID_MPI_Irecv },
   { "MPI_Type_vector",	ID_MPI_Type_vector },
   { "MPI_Exscan",	ID_MPI_Exscan },
   { "MPI_Ireduce",	ID_MPI_Ireduce },
   { "MPI_Unpack",	ID_MPI_Unpack },
   { "MPI_Fetch_and_op",	ID_MPI_Fetch_and_op },
   { "MPI_Ireduce_scatter",	ID_MPI_Ireduce_scatter },
   { "MPI_Unpack_external",	ID_MPI_Unpack_external },
   { "MPI_File_c2f",	ID_MPI_File_c2f },
   { "MPI_Ireduce_scatter_block",	ID_MPI_Ireduce_scatter_block },
   { "MPI_Unpublish_name",	ID_MPI_Unpublish_name },
   { "MPI_File_call_errhandler",	ID_MPI_File_call_errhandler },
   { "MPI_Irsend",	ID_MPI_Irsend },
   { "MPI_Wait",	ID_MPI_Wait },
   { "MPI_File_close",	ID_MPI_File_close },
   { "MPI_Is_thread_main",	ID_MPI_Is_thread_main },
   { "MPI_Waitall",	ID_MPI_Waitall },
   { "MPI_File_create_errhandler",	ID_MPI_File_create_errhandler },
   { "MPI_Iscan",	ID_MPI_Iscan },
   { "MPI_Waitany",	ID_MPI_Waitany },
   { "MPI_File_delete",	ID_MPI_File_delete },
   { "MPI_Iscatter",	ID_MPI_Iscatter },
   { "MPI_Waitsome",	ID_MPI_Waitsome },
   { "MPI_File_f2c",	ID_MPI_File_f2c },
   { "MPI_Iscatterv",	ID_MPI_Iscatterv },
   { "MPI_Win_allocate",	ID_MPI_Win_allocate },
   { "MPI_File_get_amode",	ID_MPI_File_get_amode },
   { "MPI_Isend",	ID_MPI_Isend },
   { "MPI_Win_allocate_shared",	ID_MPI_Win_allocate_shared },
   { "MPI_File_get_atomicity",	ID_MPI_File_get_atomicity },
   { "MPI_Issend",	ID_MPI_Issend },
   { "MPI_Win_attach",	ID_MPI_Win_attach },
   { "MPI_File_get_byte_offset",	ID_MPI_File_get_byte_offset },
   { "MPI_Keyval_create",	ID_MPI_Keyval_create },
   { "MPI_Win_call_errhandler",	ID_MPI_Win_call_errhandler },
   { "MPI_File_get_errhandler",	ID_MPI_File_get_errhandler },
   { "MPI_Keyval_free",	ID_MPI_Keyval_free },
   { "MPI_Win_complete",	ID_MPI_Win_complete },
   { "MPI_File_get_group",	ID_MPI_File_get_group },
   { "MPI_Lookup_name",	ID_MPI_Lookup_name },
   { "MPI_Win_create",	ID_MPI_Win_create },
   { "MPI_File_get_info",	ID_MPI_File_get_info },
   { "MPI_Mprobe",	ID_MPI_Mprobe },
   { "MPI_Win_create_dynamic",	ID_MPI_Win_create_dynamic },
   { "MPI_File_get_position",	ID_MPI_File_get_position },
   { "MPI_Mrecv",	ID_MPI_Mrecv },
   { "MPI_Win_create_errhandler",	ID_MPI_Win_create_errhandler },
   { "MPI_File_get_position_shared",	ID_MPI_File_get_position_shared },
   { "MPI_Neighbor_allgather",	ID_MPI_Neighbor_allgather },
   { "MPI_Win_create_keyval",	ID_MPI_Win_create_keyval },
   { "MPI_File_get_size",	ID_MPI_File_get_size },
   { "MPI_Neighbor_allgatherv",	ID_MPI_Neighbor_allgatherv },
   { "MPI_Win_delete_attr",	ID_MPI_Win_delete_attr },
   { "MPI_File_get_type_extent",	ID_MPI_File_get_type_extent },
   { "MPI_Neighbor_alltoall",	ID_MPI_Neighbor_alltoall },
   { "MPI_Win_detach",	ID_MPI_Win_detach },
   { "MPI_File_get_view",	ID_MPI_File_get_view },
   { "MPI_Neighbor_alltoallv",	ID_MPI_Neighbor_alltoallv },
   { "MPI_Win_fence",	ID_MPI_Win_fence },
   { "MPI_File_iread",	ID_MPI_File_iread },
   { "MPI_Neighbor_alltoallw",	ID_MPI_Neighbor_alltoallw },
   { "MPI_Win_flush",	ID_MPI_Win_flush },
   { "MPI_File_iread_all",	ID_MPI_File_iread_all },
   { "MPI_Op_commute",	ID_MPI_Op_commute },
   { "MPI_Win_flush_all",	ID_MPI_Win_flush_all },
   { "MPI_File_iread_at",	ID_MPI_File_iread_at },
   { "MPI_Op_create",	ID_MPI_Op_create },
   { "MPI_Win_flush_local",	ID_MPI_Win_flush_local },
   { "MPI_File_iread_at_all",	ID_MPI_File_iread_at_all },
   { "MPI_Op_free",	ID_MPI_Op_free },
   { "MPI_Win_flush_local_all",	ID_MPI_Win_flush_local_all },
   { "MPI_File_iread_shared",	ID_MPI_File_iread_shared },
   { "MPI_Open_port",	ID_MPI_Open_port },
   { "MPI_Win_free",	ID_MPI_Win_free },
   { "MPI_File_iwrite",	ID_MPI_File_iwrite },
   { "MPI_Pack",	ID_MPI_Pack },
   { "MPI_Win_free_keyval",	ID_MPI_Win_free_keyval },
   { "MPI_File_iwrite_all",	ID_MPI_File_iwrite_all },
   { "MPI_Pack_external",	ID_MPI_Pack_external },
   { "MPI_Win_get_attr",	ID_MPI_Win_get_attr },
   { "MPI_File_iwrite_at",	ID_MPI_File_iwrite_at },
   { "MPI_Pack_external_size",	ID_MPI_Pack_external_size },
   { "MPI_Win_get_errhandler",	ID_MPI_Win_get_errhandler },
   { "MPI_File_iwrite_at_all",	ID_MPI_File_iwrite_at_all },
   { "MPI_Pack_size",	ID_MPI_Pack_size },
   { "MPI_Win_get_group",	ID_MPI_Win_get_group },
   { "MPI_File_iwrite_shared",	ID_MPI_File_iwrite_shared },
   { "MPI_Pcontrol",	ID_MPI_Pcontrol },
   { "MPI_Win_get_info",	ID_MPI_Win_get_info },
   { "MPI_File_open",	ID_MPI_File_open },
   { "MPI_Probe",	ID_MPI_Probe },
   { "MPI_Win_get_name",	ID_MPI_Win_get_name },
   { "MPI_File_preallocate",	ID_MPI_File_preallocate },
   { "MPI_Publish_name",	ID_MPI_Publish_name },
   { "MPI_Win_lock",	ID_MPI_Win_lock },
   { "MPI_File_read",	ID_MPI_File_read },
   { "MPI_Put",	ID_MPI_Put },
   { "MPI_Win_lock_all",	ID_MPI_Win_lock_all },
   { "MPI_File_read_all",	ID_MPI_File_read_all },
   { "MPI_Query_thread",	ID_MPI_Query_thread },
   { "MPI_Win_post",	ID_MPI_Win_post },
   { "MPI_File_read_all_begin",	ID_MPI_File_read_all_begin },
   { "MPI_Raccumulate",	ID_MPI_Raccumulate },
   { "MPI_Win_set_attr",	ID_MPI_Win_set_attr },
   { "MPI_File_read_all_end",	ID_MPI_File_read_all_end },
   { "MPI_Recv",	ID_MPI_Recv },
   { "MPI_Win_set_errhandler",	ID_MPI_Win_set_errhandler },
   { "MPI_File_read_at",	ID_MPI_File_read_at },
   { "MPI_Recv_init",	ID_MPI_Recv_init },
   { "MPI_Win_set_info",	ID_MPI_Win_set_info },
   { "MPI_File_read_at_all",	ID_MPI_File_read_at_all },
   { "MPI_Reduce",	ID_MPI_Reduce },
   { "MPI_Win_set_name",	ID_MPI_Win_set_name },
   { "MPI_File_read_at_all_begin",	ID_MPI_File_read_at_all_begin },
   { "MPI_Reduce_local",	ID_MPI_Reduce_local },
   { "MPI_Win_shared_query",	ID_MPI_Win_shared_query },
   { "MPI_File_read_at_all_end",	ID_MPI_File_read_at_all_end },
   { "MPI_Reduce_scatter",	ID_MPI_Reduce_scatter },
   { "MPI_Win_start",	ID_MPI_Win_start },
   { "MPI_File_read_ordered",	ID_MPI_File_read_ordered },
   { "MPI_Reduce_scatter_block",	ID_MPI_Reduce_scatter_block },
   { "MPI_Win_sync",	ID_MPI_Win_sync },
   { "MPI_File_read_ordered_begin",	ID_MPI_File_read_ordered_begin },
   { "MPI_Register_datarep",	ID_MPI_Register_datarep },
   { "MPI_Win_test",	ID_MPI_Win_test },
   { "MPI_File_read_ordered_end",	ID_MPI_File_read_ordered_end },
   { "MPI_Request_free",	ID_MPI_Request_free },
   { "MPI_Win_unlock",	ID_MPI_Win_unlock },
   { "MPI_File_read_shared",	ID_MPI_File_read_shared },
   { "MPI_Request_get_status",	ID_MPI_Request_get_status },
   { "MPI_Win_unlock_all",	ID_MPI_Win_unlock_all },
   { "MPI_File_seek",	ID_MPI_File_seek },
   { "MPI_Rget",	ID_MPI_Rget },
   { "MPI_Win_wait",	ID_MPI_Win_wait },
   { "MPI_File_seek_shared",	ID_MPI_File_seek_shared },
   { "MPI_Rget_accumulate",	ID_MPI_Rget_accumulate },
   { "MPI_Wtick",	ID_MPI_Wtick },
   { "MPI_File_set_atomicity",	ID_MPI_File_set_atomicity },
   { "MPI_Rput",	ID_MPI_Rput },
   { "MPI_Wtime",  ID_MPI_Wtime}
})
{

}