TARGET := runsstmac
SRC := $(shell ls *.cc) $(shell ls util/*.cc)

CXX :=     sst++
CC :=      sstcc
CXXFLAGS :=
CPPFLAGS :=  -I. -Iinclude/ -Wp,-w
LIBDIR :=
PREFIX :=
LDFLAGS :=  -Wl,-rpath,$(PREFIX)/lib

OBJ := $(SRC:.cc=.o) 
OBJ := $(OBJ:.cpp=.o)
OBJ := $(OBJ:.c=.o)

.PHONY: clean install 

all: $(TARGET)

$(TARGET): $(OBJ) 
	$(CXX) -o $@ $+ $(LDFLAGS) $(LIBS) 

%.o: %.cc 
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

clean: 
  rm $(TARGET) $(OBJ)

install: $(TARGET)
	cp $< $(PREFIX)/bin

