/**
Copyright 2009-2018 National Technology and Engineering Solutions of Sandia, 
LLC (NTESS).  Under the terms of Contract DE-NA-0003525, the U.S.  Government 
retains certain rights in this software.

Sandia National Laboratories is a multimission laboratory managed and operated
by National Technology and Engineering Solutions of Sandia, LLC., a wholly 
owned subsidiary of Honeywell International, Inc., for the U.S. Department of 
Energy's National Nuclear Security Administration under contract DE-NA0003525.

Copyright (c) 2009-2018, NTESS

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.

    * Neither the name of the copyright holder nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Questions? Contact sst-macro-help@sandia.gov
*/

#include <sstmac/common/stats/stat_collector.h>
#include <sstmac/common/event_scheduler.h>
#include <sstmac/common/event_manager.h>
#include <sprockit/sim_parameters.h>
#include <sprockit/errors.h>
#include <sprockit/keyword_registration.h>

RegisterKeywords(
{ "suffix", "an optional suffix for this particular collector" },
{ "fileroot", "the root of filenames generated by this stat collector" },
);

#if !SSTMAC_INTEGRATED_SST_CORE

namespace sstmac {

SST_ELI_INSTANTIATE_STATISTIC(NullStatistic, int)
SST_ELI_INSTANTIATE_STATISTIC(NullStatistic, double)
SST_ELI_INSTANTIATE_STATISTIC(NullStatistic, uint64_t)
SST_ELI_INSTANTIATE_STATISTIC(NullStatistic, void)

StatisticBase::StatisticBase(EventScheduler *parent, const std::string &name,
                             const std::string &subName, SST::Params &params) :
  name_(name)
{
  group_ = params.find<std::string>("group", "default");
  output_ = params.find<std::string>("output", "csv");
}

void
StatisticFieldsOutput::registerStatistic(StatisticBase *stat)
{
  stat->registerOutputFields(this);
}

void
Statistic<void>::outputStatisticData(StatisticFieldsOutput *output, bool endOfSimFlag)
{
  spkt_abort_printf("void statistic '%s' should never call outputStatisticData\n"
                    "ensure that correct output is set for group '%s'",
                    name().c_str(), group().c_str());
}

void
Statistic<void>::registerOutputFields(StatisticFieldsOutput *statOutput)
{
  spkt_abort_printf("void statistic '%s' should never call registerOutputFields\n"
                    "ensure that correct output is set for group '%s'",
                    name().c_str(), group().c_str());
}

} // end of namespace sstmac

#endif
