#! /usr/bin/env python

import re
import sys

text = open(sys.argv[1]).read()
arr = text.splitlines()
print "Total of %d events" % (len(arr) - 1)
maxid = 0
for line in arr:
  idx = line.find("id=")
  if idx > 0: 
    idx += 5
    stopIdx = idx
    while not line[stopIdx] == '"':
      stopIdx += 1
    id = int(line[idx:stopIdx])
    if id > maxid: maxid = id
print maxid

#regexp = "id=(.*?) "
#matches = re.compile(regexp).findall(text)
#event_ids = [0]*len(matches)
#idx = 0
#max_event = 0
#for m in matches:
#    event_id = int(m[2:-1])
#
#
##    event_ids[idx] = event_id
##    idx += 1
#
#event_ids.sort()
#
#print event_ids[-1]

#for i in range(len(event_ids)):
#    if not event_ids[i] == i:
#        print "%d != %d" % (i, event_ids[i])
#        sys.exit()
#
