#! /usr/bin/env python

import re
import os
import sys
import commands
filename = sys.argv[1]
text = open(filename).read()

libs = {}
offsets = {}
atos = False

matches = re.compile("addr=(.*?)\s+offset=(.*?)\s+fname=(.*)").findall(text)
for addr, offset, fname in matches:
    if not fname in libs:
        libs[fname] = []
        offsets[fname] = offset
         

    if not addr in libs[fname]:
        libs[fname].append(addr)


for lib in libs:
    sys.stderr.write("%s\n" % lib)
    addrs = libs[lib]
    offset = offsets[lib]
    cmd = ""
    if atos:
        cmd = "atos -o %s -l %s %s" % (lib, offset, " ".join(addrs))
    else:
        offset_addrs = []
        for addr in addrs:
            new_addr = hex(eval(addr) - eval(offset))
            offset_addrs.append(new_addr)
        cmd = "addr2line -e %s %s" % (lib, " ".join(offset_addrs))
    translations = commands.getoutput(cmd).splitlines()
    for i in range(len(addrs)):
        translation = translations[i]
        entry = "addr=%s offset=%s fname=%s" % (addrs[i], offset, lib)
        #print entry, translation
        text = text.replace(entry, translation)

print text


