#! /usr/bin/env python

import numpy
import sys
import os
n = sys.argv[1]
N = sys.argv[2]
text = open("template.ini").read().replace("$n_rank", n).replace("$N_thread", N)
n = int(n)
N = int(N)
nnode = n / N
if n % N:
    nnode += 1


# we need nx*ny*nz >= nnode
nonethird = int(numpy.exp((numpy.log(nnode) / 3)))
ntest = nonethird*nonethird*nonethird
if ntest < nnode:
    nonethird += 1

nonethird = str(nonethird)
text = text.replace("$nx", nonethird).replace("$ny", nonethird).replace("$nz", nonethird)

open("parameters.ini", "w").write(text)
#os.system("./runshmem > %d.%d.out" % (n,N))

